[package]
name = "isaac-completion-tracker"
version = "0.1.0"
description = "Suivi de complétion local et hors-ligne pour The Binding of Isaac: Repentance+"
authors = ["reiassezbeau <https://github.com/reiassezbeau>"]
homepage = "https://github.com/reiassezbeau"
repository = "https://github.com/reiassezbeau/isaac-completion-tracker"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "isaac_completion_tracker_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
