// SPDX-License-Identifier: GPL-3.0-only
// Isaac Completion Tracker — © 2026 reiassezbeau — https://github.com/reiassezbeau

/**
 * i18n - view strings (5/5): save provenance, parser errors, the manual update
 * check, and the community links.
 *
 * The `perr.*` entries matter more than they look: the save picker used to print the
 * parser's raw Rust message, so a French UI showed English sentences (and one stray
 * French one). The backend now sends a stable code plus its technical value, and the
 * sentence is translated here while the value (an offset, a version byte) is not.
 *
 * Fallback: requested language -> English -> key.
 */
import type { Lang } from "./i18n";

type Entry = Partial<Record<Lang, string>>;

export const VIEW_STRINGS_5: Record<string, Entry> = {
  // ═══ Where a save file came from ═══
  // "Steam Cloud" is Valve's product name: identical in every language.
  "src.steam_cloud": { en: "Steam Cloud" },
  "src.documents": { en: "Documents", fr: "Documents", es: "Documentos", pt: "Documentos", de: "Dokumente", ru: "Документы", pl: "Dokumenty", zh: "文档", ja: "ドキュメント", hi: "दस्तावेज़", ar: "المستندات", bn: "ডকুমেন্টস", ur: "دستاویزات" },
  "src.backup": { en: "Local backup", fr: "Sauvegarde locale", es: "Copia local", pt: "Backup local", de: "Lokale Sicherung", ru: "Локальная копия", pl: "Kopia lokalna", zh: "本地备份", ja: "ローカルバックアップ", hi: "स्थानीय बैकअप", ar: "نسخة احتياطية محلية", bn: "স্থানীয় ব্যাকআপ", ur: "مقامی بیک اپ" },

  // ═══ Why a save could not be read ═══
  "perr.too_short": { en: "File too short to be a save", fr: "Fichier trop court pour être une sauvegarde", es: "Archivo demasiado corto para ser una partida", pt: "Arquivo curto demais para ser um save", de: "Datei zu kurz für einen Spielstand", ru: "Файл слишком мал для сохранения", pl: "Plik za krótki jak na zapis", zh: "文件过小，不是存档", ja: "ファイルが小さすぎてセーブではありません", hi: "फ़ाइल सेव होने के लिए बहुत छोटी है", ar: "الملف أصغر من أن يكون ملف حفظ", bn: "ফাইলটি সেভ হওয়ার জন্য খুব ছোট", ur: "فائل سیو ہونے کے لیے بہت چھوٹی ہے" },
  "perr.bad_header": { en: "Not a Binding of Isaac save (Repentance / Repentance+)", fr: "Ce n'est pas une sauvegarde The Binding of Isaac (Repentance / Repentance+)", es: "No es una partida de The Binding of Isaac (Repentance / Repentance+)", pt: "Não é um save de The Binding of Isaac (Repentance / Repentance+)", de: "Kein Spielstand von The Binding of Isaac (Repentance / Repentance+)", ru: "Это не сохранение The Binding of Isaac (Repentance / Repentance+)", pl: "To nie jest zapis The Binding of Isaac (Repentance / Repentance+)", zh: "不是 The Binding of Isaac 的存档（Repentance / Repentance+）", ja: "The Binding of Isaac のセーブではありません（Repentance / Repentance+）", hi: "यह The Binding of Isaac का सेव नहीं है (Repentance / Repentance+)", ar: "ليس ملف حفظ لـ The Binding of Isaac ‏(Repentance / Repentance+)", bn: "এটি The Binding of Isaac-এর সেভ নয় (Repentance / Repentance+)", ur: "یہ The Binding of Isaac کا سیو نہیں ہے (Repentance / Repentance+)" },
  "perr.unknown_version": { en: "Unknown save version - unexpected format", fr: "Version de sauvegarde inconnue — format inattendu", es: "Versión de partida desconocida — formato inesperado", pt: "Versão de save desconhecida — formato inesperado", de: "Unbekannte Spielstand-Version — unerwartetes Format", ru: "Неизвестная версия сохранения — неожиданный формат", pl: "Nieznana wersja zapisu — nieoczekiwany format", zh: "未知的存档版本 —— 格式异常", ja: "不明なセーブバージョン — 想定外の形式", hi: "अज्ञात सेव संस्करण — अप्रत्याशित प्रारूप", ar: "إصدار حفظ غير معروف — تنسيق غير متوقَّع", bn: "অজানা সেভ সংস্করণ — অপ্রত্যাশিত ফরম্যাট", ur: "نامعلوم سیو ورژن — غیر متوقع فارمیٹ" },
  "perr.out_of_bounds": { en: "Read past the end of the file (truncated or unexpected format)", fr: "Lecture au-delà de la fin du fichier (tronqué ou format inattendu)", es: "Lectura más allá del final del archivo (truncado o formato inesperado)", pt: "Leitura além do fim do arquivo (truncado ou formato inesperado)", de: "Lesen über das Dateiende hinaus (abgeschnitten oder unerwartetes Format)", ru: "Чтение за концом файла (обрезан или неожиданный формат)", pl: "Odczyt poza końcem pliku (obcięty lub nieoczekiwany format)", zh: "读取超出文件末尾（被截断或格式异常）", ja: "ファイル末尾を超えて読み込みました（切り詰め、または想定外の形式）", hi: "फ़ाइल के अंत के बाद पढ़ने का प्रयास (कटी हुई या अप्रत्याशित प्रारूप)", ar: "قراءة بعد نهاية الملف (مبتور أو تنسيق غير متوقَّع)", bn: "ফাইলের শেষের পরেও পড়া হয়েছে (ছাঁটা বা অপ্রত্যাশিত ফরম্যাট)", ur: "فائل کے اختتام سے آگے پڑھا گیا (کٹا ہوا یا غیر متوقع فارمیٹ)" },
  "perr.unreadable": { en: "The file could not be read", fr: "Le fichier n'a pas pu être lu", es: "No se pudo leer el archivo", pt: "Não foi possível ler o arquivo", de: "Die Datei konnte nicht gelesen werden", ru: "Не удалось прочитать файл", pl: "Nie udało się odczytać pliku", zh: "无法读取该文件", ja: "ファイルを読み込めませんでした", hi: "फ़ाइल पढ़ी नहीं जा सकी", ar: "تعذّرت قراءة الملف", bn: "ফাইলটি পড়া যায়নি", ur: "فائل پڑھی نہیں جا سکی" },

  // ═══ Save picker: older editions, backups, unreadable files ═══
  "slot.oldFiles": { en: "older files and backups", fr: "anciens fichiers et sauvegardes", es: "archivos antiguos y copias", pt: "arquivos antigos e backups", de: "ältere Dateien und Sicherungen", ru: "старые файлы и копии", pl: "starsze pliki i kopie", zh: "旧文件与备份", ja: "古いファイルとバックアップ", hi: "पुरानी फ़ाइलें और बैकअप", ar: "ملفات قديمة ونسخ احتياطية", bn: "পুরোনো ফাইল ও ব্যাকআপ", ur: "پرانی فائلیں اور بیک اپ" },
  "slot.oldFilesHint": { en: "Saves from earlier editions, dated backups, and files this app cannot read. Nothing is ever deleted — they are only folded away.", fr: "Sauvegardes d'éditions précédentes, backups datés et fichiers illisibles. Rien n'est jamais supprimé — ils sont seulement repliés.", es: "Partidas de ediciones anteriores, copias fechadas y archivos ilegibles. Nunca se borra nada: solo se pliegan.", pt: "Saves de edições anteriores, backups datados e arquivos ilegíveis. Nada é apagado — apenas ficam recolhidos.", de: "Spielstände älterer Editionen, datierte Sicherungen und unlesbare Dateien. Es wird nie etwas gelöscht — sie sind nur eingeklappt.", ru: "Сохранения прежних изданий, датированные копии и нечитаемые файлы. Ничего не удаляется — они просто свёрнуты.", pl: "Zapisy wcześniejszych edycji, datowane kopie i pliki nie do odczytania. Nic nie jest usuwane — są tylko zwinięte.", zh: "旧版本的存档、带日期的备份，以及无法读取的文件。绝不删除任何内容，只是折叠起来。", ja: "以前のエディションのセーブ、日付つきバックアップ、読み込めないファイルです。削除は一切せず、畳んでいるだけです。", hi: "पुराने संस्करणों के सेव, दिनांकित बैकअप और अपठनीय फ़ाइलें। कुछ भी नहीं मिटाया जाता — केवल छिपाया जाता है।", ar: "ملفات حفظ من إصدارات سابقة ونسخ احتياطية مؤرَّخة وملفات غير قابلة للقراءة. لا يُحذف شيء أبدًا — إنها مطوية فقط.", bn: "আগের সংস্করণের সেভ, তারিখযুক্ত ব্যাকআপ ও অপঠনযোগ্য ফাইল। কিছুই মুছে ফেলা হয় না — কেবল গুটিয়ে রাখা হয়।", ur: "پرانے ایڈیشنز کے سیو، تاریخ والے بیک اپ، اور ناقابلِ مطالعہ فائلیں۔ کچھ بھی حذف نہیں کیا جاتا — صرف تہہ کیا جاتا ہے۔" },

  "common.close": { en: "Close", fr: "Fermer", es: "Cerrar", pt: "Fechar", de: "Schließen", ru: "Закрыть", pl: "Zamknij", zh: "关闭", ja: "閉じる", hi: "बंद करें", ar: "إغلاق", bn: "বন্ধ করুন", ur: "بند کریں" },

  // ═══ Community ═══
  "about.community": { en: "Community", fr: "Communauté", es: "Comunidad", pt: "Comunidade", de: "Community", ru: "Сообщество", pl: "Społeczność", zh: "社区", ja: "コミュニティ", hi: "समुदाय", ar: "المجتمع", bn: "কমিউনিটি", ur: "کمیونٹی" },
  "about.discordBody": { en: "Questions, a bug to report, or just want to compare Dead God runs? The Discord is the place.", fr: "Des questions, un bug à signaler, ou envie de comparer vos runs Dead God ? C'est sur le Discord.", es: "¿Dudas, un fallo que reportar o ganas de comparar runs hacia Dead God? El Discord es el sitio.", pt: "Dúvidas, um bug para relatar ou vontade de comparar runs rumo ao Dead God? O Discord é o lugar.", de: "Fragen, ein Bug oder einfach Lust, Dead-God-Runs zu vergleichen? Dafür gibt es den Discord.", ru: "Вопросы, баг или желание сравнить забеги к Dead God? Всё это — в Discord.", pl: "Pytania, błąd do zgłoszenia albo ochota porównać runy do Dead God? Discord to właściwe miejsce.", zh: "有疑问、想报告 bug，或者想比比 Dead God 进度？来 Discord 吧。", ja: "質問、バグ報告、Dead God の進捗自慢まで — Discord へどうぞ。", hi: "सवाल, बग रिपोर्ट, या Dead God रन की तुलना? Discord सही जगह है।", ar: "أسئلة أو بلاغ عن خلل أو رغبة في مقارنة جولات Dead God؟ ديسكورد هو المكان.", bn: "প্রশ্ন, বাগ রিপোর্ট, বা Dead God রান মেলাতে চান? Discord-ই ঠিক জায়গা।", ur: "سوالات، بگ رپورٹ، یا Dead God رنز کا موازنہ؟ Discord صحیح جگہ ہے۔" },
  "about.joinDiscord": { en: "Join the Discord", fr: "Rejoindre le Discord", es: "Unirse al Discord", pt: "Entrar no Discord", de: "Dem Discord beitreten", ru: "Присоединиться к Discord", pl: "Dołącz do Discorda", zh: "加入 Discord", ja: "Discord に参加", hi: "Discord से जुड़ें", ar: "انضم إلى ديسكورد", bn: "Discord-এ যোগ দিন", ur: "Discord میں شامل ہوں" },

  // ═══ Manual update check ═══
  "upd.title": { en: "Updates", fr: "Mises à jour", es: "Actualizaciones", pt: "Atualizações", de: "Updates", ru: "Обновления", pl: "Aktualizacje", zh: "更新", ja: "アップデート", hi: "अपडेट", ar: "التحديثات", bn: "আপডেট", ur: "اپ ڈیٹس" },
  "upd.intro": { en: "This app is offline: it never looks for updates on its own. Press the button when you want to check — that is the only moment anything leaves your machine, and only the public release list is requested.", fr: "Cette app est hors-ligne : elle ne cherche jamais de mise à jour toute seule. Clique quand tu veux vérifier — c'est le seul moment où quelque chose sort de ta machine, et seule la liste publique des versions est demandée.", es: "Esta app es offline: nunca busca actualizaciones por su cuenta. Pulsa el botón cuando quieras comprobar — es el único momento en que algo sale de tu equipo, y solo se pide la lista pública de versiones.", pt: "Este app é offline: nunca procura atualizações sozinho. Clique quando quiser verificar — é o único momento em que algo sai da sua máquina, e só a lista pública de versões é solicitada.", de: "Diese App ist offline: Sie sucht nie von selbst nach Updates. Drücke den Knopf, wenn du nachsehen willst — nur dann verlässt überhaupt etwas deinen Rechner, und abgefragt wird nur die öffentliche Versionsliste.", ru: "Приложение работает офлайн и никогда не ищет обновления само. Нажмите кнопку, когда захотите проверить — только в этот момент что-либо покидает ваш компьютер, и запрашивается лишь публичный список версий.", pl: "Ta aplikacja działa offline: nigdy sama nie szuka aktualizacji. Naciśnij przycisk, gdy chcesz sprawdzić — tylko wtedy cokolwiek opuszcza twój komputer, i pobierana jest wyłącznie publiczna lista wydań.", zh: "本应用离线运行，绝不会自行检查更新。想查看时点一下按钮——那是唯一有数据离开你电脑的时刻，且只请求公开的版本列表。", ja: "このアプリはオフラインで動作し、自動でアップデートを探すことはありません。確認したいときにボタンを押してください — 何かが端末の外に出るのはその瞬間だけで、要求するのは公開のリリース一覧のみです。", hi: "यह ऐप ऑफ़लाइन है: यह अपने आप कभी अपडेट नहीं खोजता। जब देखना हो तब बटन दबाएँ — केवल तभी कुछ आपकी मशीन से बाहर जाता है, और केवल सार्वजनिक रिलीज़ सूची माँगी जाती है।", ar: "هذا التطبيق يعمل دون اتصال ولا يبحث عن التحديثات من تلقاء نفسه. اضغط الزر عندما تريد التحقق — تلك هي اللحظة الوحيدة التي يغادر فيها أي شيء جهازك، ولا يُطلب سوى قائمة الإصدارات العامة.", bn: "এই অ্যাপটি অফলাইন: এটি নিজে থেকে কখনও আপডেট খোঁজে না। দেখতে চাইলে বোতামে চাপুন — কেবল তখনই কিছু আপনার মেশিন ছাড়ে, এবং কেবল প্রকাশ্য রিলিজ তালিকা চাওয়া হয়।", ur: "یہ ایپ آف لائن ہے: یہ خود کبھی اپ ڈیٹ نہیں ڈھونڈتی۔ جب دیکھنا ہو تو بٹن دبائیں — صرف اسی وقت کوئی چیز آپ کی مشین سے باہر جاتی ہے، اور صرف عوامی ریلیز فہرست مانگی جاتی ہے۔" },
  "upd.checkBtn": { en: "Check for updates", fr: "Vérifier les mises à jour", es: "Buscar actualizaciones", pt: "Procurar atualizações", de: "Nach Updates suchen", ru: "Проверить обновления", pl: "Sprawdź aktualizacje", zh: "检查更新", ja: "アップデートを確認", hi: "अपडेट जाँचें", ar: "التحقق من التحديثات", bn: "আপডেট দেখুন", ur: "اپ ڈیٹ چیک کریں" },
  "upd.upToDate": { en: "You are on the latest version", fr: "Tu es déjà à jour", es: "Ya tienes la última versión", pt: "Você já está na versão mais recente", de: "Du hast die neueste Version", ru: "У вас последняя версия", pl: "Masz najnowszą wersję", zh: "已是最新版本", ja: "最新バージョンです", hi: "आप नवीनतम संस्करण पर हैं", ar: "أنت على أحدث إصدار", bn: "আপনি সর্বশেষ সংস্করণে আছেন", ur: "آپ تازہ ترین ورژن پر ہیں" },
  "upd.checkFailed": { en: "Could not reach GitHub:", fr: "Impossible de joindre GitHub :", es: "No se pudo contactar con GitHub:", pt: "Não foi possível acessar o GitHub:", de: "GitHub war nicht erreichbar:", ru: "Не удалось связаться с GitHub:", pl: "Nie udało się połączyć z GitHubem:", zh: "无法连接 GitHub：", ja: "GitHub に接続できませんでした:", hi: "GitHub तक नहीं पहुँच सके:", ar: "تعذّر الوصول إلى GitHub:", bn: "GitHub-এ পৌঁছানো যায়নি:", ur: "GitHub تک رسائی نہ ہو سکی:" },
  "upd.newVersion": { en: "New version available:", fr: "Nouvelle version disponible :", es: "Nueva versión disponible:", pt: "Nova versão disponível:", de: "Neue Version verfügbar:", ru: "Доступна новая версия:", pl: "Dostępna nowa wersja:", zh: "有新版本：", ja: "新しいバージョンがあります:", hi: "नया संस्करण उपलब्ध:", ar: "إصدار جديد متاح:", bn: "নতুন সংস্করণ উপলব্ধ:", ur: "نیا ورژن دستیاب:" },
  "upd.downloadBtn": { en: "Download", fr: "Télécharger", es: "Descargar", pt: "Baixar", de: "Herunterladen", ru: "Скачать", pl: "Pobierz", zh: "下载", ja: "ダウンロード", hi: "डाउनलोड", ar: "تنزيل", bn: "ডাউনলোড", ur: "ڈاؤن لوڈ" },
  "upd.downloadFailed": { en: "Download failed:", fr: "Échec du téléchargement :", es: "Fallo la descarga:", pt: "Falha no download:", de: "Download fehlgeschlagen:", ru: "Ошибка загрузки:", pl: "Pobieranie nie powiodło się:", zh: "下载失败：", ja: "ダウンロードに失敗しました:", hi: "डाउनलोड विफल:", ar: "فشل التنزيل:", bn: "ডাউনলোড ব্যর্থ:", ur: "ڈاؤن لوڈ ناکام:" },
  "upd.installBtn": { en: "Install and restart", fr: "Installer et relancer", es: "Instalar y reiniciar", pt: "Instalar e reiniciar", de: "Installieren und neu starten", ru: "Установить и перезапустить", pl: "Zainstaluj i uruchom ponownie", zh: "安装并重启", ja: "インストールして再起動", hi: "इंस्टॉल कर फिर से चालू करें", ar: "التثبيت وإعادة التشغيل", bn: "ইনস্টল করে পুনরায় চালু করুন", ur: "انسٹال کر کے دوبارہ چلائیں" },
  "upd.installFailed": { en: "Could not start the installer:", fr: "Impossible de lancer l'installeur :", es: "No se pudo iniciar el instalador:", pt: "Não foi possível iniciar o instalador:", de: "Das Installationsprogramm ließ sich nicht starten:", ru: "Не удалось запустить установщик:", pl: "Nie udało się uruchomić instalatora:", zh: "无法启动安装程序：", ja: "インストーラーを起動できませんでした:", hi: "इंस्टॉलर चालू नहीं हो सका:", ar: "تعذّر تشغيل المُثبِّت:", bn: "ইনস্টলার চালু করা যায়নি:", ur: "انسٹالر چلایا نہیں جا سکا:" },
  "upd.openPage": { en: "Open the release page", fr: "Ouvrir la page de la version", es: "Abrir la página de la versión", pt: "Abrir a página da versão", de: "Release-Seite öffnen", ru: "Открыть страницу релиза", pl: "Otwórz stronę wydania", zh: "打开发布页面", ja: "リリースページを開く", hi: "रिलीज़ पेज खोलें", ar: "فتح صفحة الإصدار", bn: "রিলিজ পেজ খুলুন", ur: "ریلیز صفحہ کھولیں" },
  "upd.verified": { en: "Checksum verified — ready to install", fr: "Somme de contrôle vérifiée — prêt à installer", es: "Suma de verificación comprobada — listo para instalar", pt: "Checksum verificado — pronto para instalar", de: "Prüfsumme verifiziert — bereit zur Installation", ru: "Контрольная сумма проверена — можно устанавливать", pl: "Suma kontrolna zweryfikowana — można instalować", zh: "校验和已验证 —— 可以安装", ja: "チェックサムを検証しました — インストールできます", hi: "चेकसम सत्यापित — इंस्टॉल के लिए तैयार", ar: "تم التحقق من المجموع الاختباري — جاهز للتثبيت", bn: "চেকসাম যাচাই হয়েছে — ইনস্টলের জন্য প্রস্তুত", ur: "چیک سم تصدیق شدہ — انسٹال کے لیے تیار" },
  "upd.noChecksum": { en: "This release publishes no checksum, so it cannot be installed from here. Use the release page instead.", fr: "Cette version ne publie pas de somme de contrôle : impossible de l'installer d'ici. Passe par la page de la version.", es: "Esta versión no publica suma de verificación, así que no puede instalarse desde aquí. Usa la página de la versión.", pt: "Esta versão não publica checksum, então não pode ser instalada daqui. Use a página da versão.", de: "Diese Version veröffentlicht keine Prüfsumme und kann daher nicht von hier installiert werden. Nutze die Release-Seite.", ru: "Для этого релиза не опубликована контрольная сумма, поэтому установить его отсюда нельзя. Воспользуйтесь страницей релиза.", pl: "To wydanie nie publikuje sumy kontrolnej, więc nie można go stąd zainstalować. Skorzystaj ze strony wydania.", zh: "该版本未发布校验和，因此无法从这里安装。请使用发布页面。", ja: "このリリースはチェックサムを公開していないため、ここからはインストールできません。リリースページをご利用ください。", hi: "इस रिलीज़ में चेकसम नहीं है, इसलिए इसे यहाँ से इंस्टॉल नहीं किया जा सकता। रिलीज़ पेज का उपयोग करें।", ar: "هذا الإصدار لا ينشر مجموعًا اختباريًا، لذا لا يمكن تثبيته من هنا. استخدم صفحة الإصدار.", bn: "এই রিলিজে চেকসাম নেই, তাই এখান থেকে ইনস্টল করা যাবে না। রিলিজ পেজ ব্যবহার করুন।", ur: "اس ریلیز میں چیک سم شائع نہیں کیا گیا، اس لیے یہاں سے انسٹال نہیں ہو سکتا۔ ریلیز صفحہ استعمال کریں۔" },
  "upd.confirmTitle": { en: "Install the update?", fr: "Installer la mise à jour ?", es: "¿Instalar la actualización?", pt: "Instalar a atualização?", de: "Update installieren?", ru: "Установить обновление?", pl: "Zainstalować aktualizację?", zh: "安装此更新？", ja: "アップデートをインストールしますか？", hi: "अपडेट इंस्टॉल करें?", ar: "تثبيت التحديث؟", bn: "আপডেট ইনস্টল করবেন?", ur: "اپ ڈیٹ انسٹال کریں؟" },
  "upd.confirmBody": { en: "The app will close so the installer can replace its files. Your save, your overrides and the mod's run history are left untouched.", fr: "L'app va se fermer pour que l'installeur remplace ses fichiers. Ta sauvegarde, tes corrections et l'historique de runs du mod ne sont pas touchés.", es: "La app se cerrará para que el instalador reemplace sus archivos. Tu partida, tus correcciones y el historial de runs del mod no se tocan.", pt: "O app vai fechar para o instalador substituir seus arquivos. Seu save, suas correções e o histórico de runs do mod ficam intactos.", de: "Die App schließt sich, damit das Installationsprogramm ihre Dateien ersetzen kann. Dein Spielstand, deine Korrekturen und der Run-Verlauf der Mod bleiben unberührt.", ru: "Приложение закроется, чтобы установщик мог заменить его файлы. Сохранение, ваши правки и история забегов мода останутся нетронутыми.", pl: "Aplikacja zamknie się, aby instalator mógł podmienić jej pliki. Twój zapis, korekty i historia runów moda pozostają nietknięte.", zh: "应用将关闭，以便安装程序替换其文件。你的存档、手动修正和模组的运行历史都不会被改动。", ja: "インストーラーがファイルを置き換えられるよう、アプリを終了します。セーブ、手動修正、Mod のラン履歴には一切触れません。", hi: "इंस्टॉलर फ़ाइलें बदल सके इसलिए ऐप बंद होगा। आपका सेव, आपके सुधार और मॉड का रन इतिहास अछूते रहते हैं।", ar: "سيُغلق التطبيق ليتمكن المُثبِّت من استبدال ملفاته. ملف الحفظ والتصحيحات وسجل جولات المود تبقى دون مساس.", bn: "ইনস্টলার যেন ফাইল বদলাতে পারে সে জন্য অ্যাপটি বন্ধ হবে। আপনার সেভ, সংশোধন ও মডের রান ইতিহাস অক্ষত থাকে।", ur: "ایپ بند ہو جائے گی تاکہ انسٹالر اس کی فائلیں بدل سکے۔ آپ کا سیو، تصحیحات اور ماڈ کی رن ہسٹری محفوظ رہتی ہیں۔" },
};
