// SPDX-License-Identifier: GPL-3.0-only
// Isaac Completion Tracker — © 2026 reiassezbeau — https://github.com/reiassezbeau

/**
 * i18n - view strings (6/6): the build assistant's analysis lines.
 *
 * These used to be English sentences built in Rust and rendered as-is, so the whole
 * strengths/weaknesses panel stayed English in all 13 languages. The backend now
 * sends `Note { code, params }` and the wording lives here - the same contract the
 * `perr.*` entries use for parser errors.
 *
 * Placeholders are `{name}` and are substituted by `noteText()` in the view.
 * `{flag}` arrives as a raw tear-flag id and is translated through `tflag.*` first.
 *
 * Fallback: requested language -> English -> key.
 */

import type { Lang } from "./i18n";

type Entry = Partial<Record<Lang, string>>;

export const VIEW_STRINGS_6: Record<string, Entry> = {
  // ═══ Build analysis - archetypes and strengths ═══
  "bldn.glass_cannon": { en: "Glass cannon: big damage but low fire rate.", fr: "Château de cartes : gros dégâts mais cadence faible.", es: "Cañón de cristal: mucho daño pero cadencia baja.", pt: "Canhão de vidro: dano alto mas cadência baixa.", de: "Glaskanone: viel Schaden, aber niedrige Feuerrate.", ru: "Хрупкая пушка: большой урон, но низкая скорострельность.", pl: "Szklana armata: duże obrażenia, ale niska szybkostrzelność.", zh: "玻璃大炮：伤害很高但射速很低。", ja: "グラスキャノン：火力は高いが連射力が低い。", hi: "ग्लास कैनन: भारी नुकसान पर फायर रेट कम।", ar: "مدفع زجاجي: ضرر كبير لكن معدل إطلاق منخفض.", bn: "গ্লাস ক্যানন: বড় ক্ষতি কিন্তু ফায়ার রেট কম।", ur: "گلاس کینن: نقصان زیادہ مگر فائر ریٹ کم۔" },
  "bldn.big_damage": { en: "Very high damage per shot.", fr: "Dégâts par tir très élevés.", es: "Daño por disparo muy alto.", pt: "Dano por tiro muito alto.", de: "Sehr hoher Schaden pro Schuss.", ru: "Очень высокий урон за выстрел.", pl: "Bardzo wysokie obrażenia na strzał.", zh: "单发伤害非常高。", ja: "一発あたりのダメージが非常に高い。", hi: "प्रति शॉट नुकसान बहुत अधिक।", ar: "ضرر مرتفع جدًا لكل طلقة.", bn: "প্রতি শটে ক্ষতি খুব বেশি।", ur: "فی شاٹ نقصان بہت زیادہ۔" },
  "bldn.have_flag": { en: "You have {flag} tears.", fr: "Tu as des larmes {flag}.", es: "Tienes lágrimas {flag}.", pt: "Você tem lágrimas {flag}.", de: "Du hast {flag} Tränen.", ru: "У вас слёзы: {flag}.", pl: "Masz łzy {flag}.", zh: "你拥有{flag}眼泪。", ja: "{flag}の涙を持っている。", hi: "आपके पास {flag} आँसू हैं।", ar: "لديك دموع {flag}.", bn: "আপনার {flag} অশ্রু আছে।", ur: "آپ کے پاس {flag} آنسو ہیں۔" },
  "bldn.familiar_flag": { en: "Your familiar fires {flag} tears — your own tears do not.", fr: "Ton familier tire des larmes {flag} — les tiennes, non.", es: "Tu familiar dispara lágrimas {flag} — las tuyas no.", pt: "Seu familiar atira lágrimas {flag} — as suas não.", de: "Dein Begleiter schießt {flag} Tränen — deine eigenen nicht.", ru: "Ваш спутник стреляет слезами {flag} — ваши собственные нет.", pl: "Twój chowaniec strzela łzami {flag} — twoje własne nie.", zh: "你的跟班发射{flag}眼泪——你自己的不会。", ja: "使い魔が{flag}の涙を撃つ — 自分の涙は違う。", hi: "आपका फ़ैमिलियर {flag} आँसू दागता है — आपके अपने नहीं।", ar: "تابعك يطلق دموع {flag} — أما دموعك أنت فلا.", bn: "আপনার ফ্যামিলিয়ার {flag} অশ্রু ছোড়ে — আপনার নিজের নয়।", ur: "آپ کا فیملیئر {flag} آنسو داغتا ہے — آپ کے اپنے نہیں۔" },
  "bldn.have_flight": { en: "You have flight.", fr: "Tu as le vol.", es: "Tienes vuelo.", pt: "Você tem voo.", de: "Du kannst fliegen.", ru: "У вас есть полёт.", pl: "Masz latanie.", zh: "你拥有飞行。", ja: "飛行を持っている。", hi: "आपके पास उड़ान है।", ar: "لديك الطيران.", bn: "আপনার উড়ান আছে।", ur: "آپ کے پاس پرواز ہے۔" },
  "bldn.have_flight_character": { en: "Your character flies on its own — no item needed.", fr: "Ton personnage vole d'origine — aucun objet nécessaire.", es: "Tu personaje vuela de serie — no hace falta ningún objeto.", pt: "Seu personagem voa por natureza — nenhum item necessário.", de: "Deine Figur fliegt von Haus aus — kein Gegenstand nötig.", ru: "Ваш персонаж летает сам по себе — предмет не нужен.", pl: "Twoja postać lata sama z siebie — żaden przedmiot nie jest potrzebny.", zh: "你的角色天生会飞——不需要道具。", ja: "キャラクター自身が飛行できる — アイテム不要。", hi: "आपका किरदार स्वयं उड़ता है — किसी वस्तु की ज़रूरत नहीं।", ar: "شخصيتك تطير بطبيعتها — دون حاجة إلى أي غرض.", bn: "আপনার চরিত্র নিজেই ওড়ে — কোনো আইটেম লাগে না।", ur: "آپ کا کردار خود اڑتا ہے — کسی آئٹم کی ضرورت نہیں۔" },
  "bldn.familiars_dps": { en: "{n} familiar(s) adding extra DPS.", fr: "{n} familier(s) qui ajoutent des DPS.", es: "{n} familiar(es) que añaden DPS extra.", pt: "{n} familiar(es) somando DPS extra.", de: "{n} Begleiter mit zusätzlichem DPS.", ru: "{n} спутник(ов) добавляют урон в секунду.", pl: "{n} chowaniec(ów) dokłada dodatkowe DPS.", zh: "{n} 个跟班提供额外 DPS。", ja: "使い魔 {n} 体が追加 DPS を出している。", hi: "{n} फ़ैमिलियर अतिरिक्त DPS जोड़ रहे हैं।", ar: "{n} تابع يضيف ضررًا إضافيًا في الثانية.", bn: "{n} ফ্যামিলিয়ার বাড়তি DPS দিচ্ছে।", ur: "{n} فیملیئر اضافی DPS دے رہے ہیں۔" },

  // ═══ Build analysis - weaknesses ═══
  "bldn.redundant_flag": { en: "Redundant: {n} sources of {flag} (diminishing returns).", fr: "Redondant : {n} sources de {flag} (rendement décroissant).", es: "Redundante: {n} fuentes de {flag} (rendimiento decreciente).", pt: "Redundante: {n} fontes de {flag} (retorno decrescente).", de: "Redundant: {n} Quellen für {flag} (abnehmender Ertrag).", ru: "Избыточно: {n} источников {flag} (убывающая отдача).", pl: "Nadmiarowe: {n} źródeł {flag} (malejący zwrot).", zh: "冗余：{n} 个{flag}来源（收益递减）。", ja: "重複：{flag}の供給源が {n} 個（効果は逓減）。", hi: "अनावश्यक: {flag} के {n} स्रोत (घटता प्रतिफल)।", ar: "تكرار: {n} مصادر لـ {flag} (عائد متناقص).", bn: "অপ্রয়োজনীয়: {flag}-এর {n}টি উৎস (ক্রমহ্রাসমান ফল)।", ur: "غیر ضروری: {flag} کے {n} ذرائع (گھٹتا فائدہ)۔" },
  "bldn.tears_replacement": { en: "{items} replace your tears — they interact, and only one shot type comes out.", fr: "{items} remplacent tes larmes — ils interagissent, et un seul type de tir en sort.", es: "{items} reemplazan tus lágrimas — interactúan y solo sale un tipo de disparo.", pt: "{items} substituem suas lágrimas — eles interagem e sai apenas um tipo de tiro.", de: "{items} ersetzen deine Tränen — sie beeinflussen sich, und nur eine Schussart kommt heraus.", ru: "{items} заменяют ваши слёзы — они взаимодействуют, и на выходе только один тип выстрела.", pl: "{items} zastępują twoje łzy — oddziałują na siebie i wychodzi tylko jeden typ strzału.", zh: "{items} 会替换你的眼泪——它们相互作用，最终只会有一种射击方式。", ja: "{items} が涙を置き換える — 互いに影響し、出てくる弾は一種類だけ。", hi: "{items} आपके आँसुओं की जगह लेते हैं — ये आपस में क्रिया करते हैं और केवल एक ही शॉट निकलता है।", ar: "{items} تستبدل دموعك — تتفاعل معًا ولا يخرج سوى نوع واحد من الطلقات.", bn: "{items} আপনার অশ্রু প্রতিস্থাপন করে — এরা পরস্পর ক্রিয়া করে, বেরোয় কেবল এক ধরনের শট।", ur: "{items} آپ کے آنسو بدل دیتے ہیں — یہ آپس میں اثر ڈالتے ہیں اور صرف ایک قسم کا شاٹ نکلتا ہے۔" },
  "bldn.no_flight": { en: "No flight (mobility gap).", fr: "Pas de vol (trou en mobilité).", es: "Sin vuelo (hueco de movilidad).", pt: "Sem voo (lacuna de mobilidade).", de: "Kein Flug (Lücke bei der Mobilität).", ru: "Нет полёта (пробел в мобильности).", pl: "Brak latania (luka w mobilności).", zh: "没有飞行（机动性缺口）。", ja: "飛行なし（機動力の穴）。", hi: "उड़ान नहीं (गतिशीलता में कमी)।", ar: "لا طيران (ثغرة في الحركة).", bn: "উড়ান নেই (গতিশীলতার ঘাটতি)।", ur: "پرواز نہیں (نقل و حرکت کا خلا)۔" },
  "bldn.no_flight_items": { en: "No flight from your items — pick your character to know for sure.", fr: "Aucun vol venant de tes objets — choisis ton personnage pour en être sûr.", es: "Ningún objeto te da vuelo — elige tu personaje para estar seguro.", pt: "Nenhum item lhe dá voo — escolha seu personagem para ter certeza.", de: "Kein Gegenstand verleiht Flug — wähle deine Figur, um sicherzugehen.", ru: "Полёт не даёт ни один предмет — выберите персонажа, чтобы знать точно.", pl: "Żaden przedmiot nie daje latania — wybierz postać, aby mieć pewność.", zh: "你的道具都不提供飞行——选择角色才能确定。", ja: "アイテムからの飛行はなし — 確かめるにはキャラクターを選択。", hi: "आपकी किसी वस्तु से उड़ान नहीं — पक्का जानने के लिए किरदार चुनें।", ar: "لا طيران من أغراضك — اختر شخصيتك للتأكد.", bn: "আপনার আইটেম থেকে উড়ান নেই — নিশ্চিত হতে চরিত্র বেছে নিন।", ur: "آپ کے آئٹمز سے پرواز نہیں — یقین کے لیے کردار منتخب کریں۔" },
  "bldn.no_crowd_control": { en: "No crowd control (no piercing/homing/explosive tears, no offensive familiar).", fr: "Pas de contrôle de foule (ni larmes perforantes/à tête chercheuse/explosives, ni familier offensif).", es: "Sin control de masas (sin lágrimas perforantes/teledirigidas/explosivas, sin familiar ofensivo).", pt: "Sem controle de multidão (sem lágrimas perfurantes/teleguiadas/explosivas, sem familiar ofensivo).", de: "Keine Massenkontrolle (keine durchdringenden/zielsuchenden/explosiven Tränen, kein offensiver Begleiter).", ru: "Нет контроля толпы (нет пробивающих/самонаводящихся/взрывных слёз, нет атакующего спутника).", pl: "Brak kontroli tłumu (bez łez przebijających/naprowadzanych/wybuchowych, bez ofensywnego chowańca).", zh: "没有群体控制（无穿透／追踪／爆炸眼泪，也无进攻型跟班）。", ja: "範囲制圧力なし（貫通・追尾・爆発の涙も攻撃的な使い魔もない）。", hi: "भीड़ नियंत्रण नहीं (न भेदने/लक्ष्य-खोजी/विस्फोटक आँसू, न आक्रामक फ़ैमिलियर)।", ar: "لا سيطرة على الحشود (لا دموع خارقة/موجهة/متفجرة، ولا تابع هجومي).", bn: "ভিড় নিয়ন্ত্রণ নেই (ভেদকারী/লক্ষ্যানুসন্ধানী/বিস্ফোরক অশ্রু নেই, আক্রমণাত্মক ফ্যামিলিয়ারও নেই)।", ur: "ہجوم پر قابو نہیں (نہ چھیدنے/نشانہ ڈھونڈنے/دھماکہ خیز آنسو، نہ حملہ آور فیملیئر)۔" },

  // ═══ "Try an item" - verdicts ═══
  "bldn.undocumented_replacement": { en: "Also replaces your tears, like {items}. Isaac resolves this pair itself — some combinations merge, others let one item take over — and this one is not documented in the knowledge base.", fr: "Remplace aussi tes larmes, comme {items}. Isaac tranche lui-même ce duo — certaines combinaisons fusionnent, d'autres laissent un objet prendre le dessus — et celle-ci n'est pas documentée dans la base.", es: "También reemplaza tus lágrimas, como {items}. Isaac resuelve ese par por su cuenta — algunas combinaciones se fusionan, otras dejan que un objeto se imponga — y esta no está documentada en la base.", pt: "Também substitui suas lágrimas, como {items}. O Isaac resolve esse par sozinho — algumas combinações se fundem, outras deixam um item dominar — e esta não está documentada na base.", de: "Ersetzt ebenfalls deine Tränen, wie {items}. Isaac entscheidet dieses Paar selbst — manche Kombinationen verschmelzen, bei anderen setzt sich ein Gegenstand durch — und diese ist in der Wissensbasis nicht dokumentiert.", ru: "Тоже заменяет ваши слёзы, как {items}. Isaac разрешает эту пару сам — какие-то сочетания сливаются, в других побеждает один предмет — а эта в базе знаний не описана.", pl: "Również zastępuje twoje łzy, jak {items}. Isaac sam rozstrzyga tę parę — niektóre kombinacje się łączą, w innych jeden przedmiot przejmuje kontrolę — a ta nie jest udokumentowana w bazie.", zh: "它同样会替换你的眼泪，和 {items} 一样。这一组由 Isaac 自行决定——有些组合会融合，有些则由其中一个接管——而这一组在知识库中没有记录。", ja: "{items} と同じく涙を置き換える。この組み合わせは Isaac 側が解決する — 融合するものもあれば片方が上書きするものもある — が、この組は知識ベースに記載がない。", hi: "यह भी आपके आँसुओं की जगह लेता है, {items} की तरह। इस जोड़ी को Isaac स्वयं तय करता है — कुछ संयोजन मिल जाते हैं, कुछ में एक वस्तु हावी हो जाती है — और यह जोड़ी ज्ञान-कोश में दर्ज नहीं है।", ar: "يستبدل دموعك أيضًا، مثل {items}. لعبة Isaac هي من تحسم هذا الاقتران — بعض التركيبات تندمج وأخرى يغلب فيها غرض واحد — وهذا الاقتران غير موثّق في قاعدة المعرفة.", bn: "এটিও আপনার অশ্রু প্রতিস্থাপন করে, {items}-এর মতো। এই জুটি Isaac নিজেই মীমাংসা করে — কিছু সংমিশ্রণ মিশে যায়, কিছুতে একটি আইটেম প্রাধান্য পায় — আর এটি জ্ঞানভাণ্ডারে নথিভুক্ত নয়।", ur: "یہ بھی آپ کے آنسو بدلتا ہے، {items} کی طرح۔ اس جوڑی کا فیصلہ Isaac خود کرتا ہے — کچھ امتزاج مل جاتے ہیں، کچھ میں ایک آئٹم حاوی ہو جاتا ہے — اور یہ جوڑی نالج بیس میں درج نہیں۔" },
  "bldn.v_conflict": { en: "Conflicts with your current build — think twice before taking it.", fr: "En conflit avec ton build actuel — réfléchis à deux fois avant de le prendre.", es: "Entra en conflicto con tu build actual — piénsalo dos veces antes de cogerlo.", pt: "Conflita com seu build atual — pense duas vezes antes de pegar.", de: "Steht im Konflikt mit deinem aktuellen Build — überlege es dir zweimal.", ru: "Конфликтует с текущей сборкой — подумайте дважды, прежде чем брать.", pl: "Koliduje z twoim obecnym buildem — zastanów się dwa razy.", zh: "与你当前的 build 冲突——拿之前三思。", ja: "現在のビルドと衝突する — 取る前によく考えること。", hi: "आपके मौजूदा बिल्ड से टकराव — लेने से पहले दो बार सोचें।", ar: "يتعارض مع بنيتك الحالية — فكّر مرتين قبل أخذه.", bn: "আপনার বর্তমান বিল্ডের সঙ্গে সংঘাত — নেওয়ার আগে দুবার ভাবুন।", ur: "آپ کے موجودہ بلڈ سے ٹکراؤ — لینے سے پہلے دو بار سوچیں۔" },
  "bldn.v_strong": { en: "Strong synergy with what you already have — good pick.", fr: "Grosse synergie avec ce que tu as déjà — bon choix.", es: "Fuerte sinergia con lo que ya tienes — buena elección.", pt: "Forte sinergia com o que você já tem — boa escolha.", de: "Starke Synergie mit dem, was du schon hast — gute Wahl.", ru: "Сильная синергия с тем, что уже есть — хороший выбор.", pl: "Silna synergia z tym, co już masz — dobry wybór.", zh: "与你已有的道具有强力联动——值得拿。", ja: "手持ちとの強いシナジーあり — good pick。", hi: "आपके पास जो है उससे मज़बूत तालमेल — अच्छा चुनाव।", ar: "تآزر قوي مع ما لديك — اختيار جيد.", bn: "আপনার যা আছে তার সঙ্গে শক্তিশালী সমন্বয় — ভালো পছন্দ।", ur: "آپ کے موجودہ سامان سے مضبوط ہم آہنگی — اچھا انتخاب۔" },
  "bldn.v_fills_gap": { en: "Fills a gap: adds {flags}.", fr: "Comble un trou : ajoute {flags}.", es: "Llena un hueco: añade {flags}.", pt: "Preenche uma lacuna: adiciona {flags}.", de: "Schließt eine Lücke: bringt {flags}.", ru: "Закрывает пробел: добавляет {flags}.", pl: "Wypełnia lukę: dodaje {flags}.", zh: "补上缺口：新增 {flags}。", ja: "穴を埋める：{flags} を追加。", hi: "कमी पूरी करता है: {flags} जोड़ता है।", ar: "يسدّ ثغرة: يضيف {flags}.", bn: "ঘাটতি পূরণ করে: {flags} যোগ করে।", ur: "خلا پُر کرتا ہے: {flags} شامل کرتا ہے۔" },
  "bldn.v_fills_gap_flight": { en: "Fills a gap: adds flight.", fr: "Comble un trou : ajoute le vol.", es: "Llena un hueco: añade vuelo.", pt: "Preenche uma lacuna: adiciona voo.", de: "Schließt eine Lücke: bringt Flug.", ru: "Закрывает пробел: добавляет полёт.", pl: "Wypełnia lukę: dodaje latanie.", zh: "补上缺口：新增飞行。", ja: "穴を埋める：飛行を追加。", hi: "कमी पूरी करता है: उड़ान जोड़ता है।", ar: "يسدّ ثغرة: يضيف الطيران.", bn: "ঘাটতি পূরণ করে: উড়ান যোগ করে।", ur: "خلا پُر کرتا ہے: پرواز شامل کرتا ہے۔" },
  "bldn.v_redundant": { en: "Redundant: you already have these tear modifiers.", fr: "Redondant : tu as déjà ces modificateurs de larmes.", es: "Redundante: ya tienes esos modificadores de lágrimas.", pt: "Redundante: você já tem esses modificadores de lágrimas.", de: "Redundant: Diese Tränen-Modifikatoren hast du bereits.", ru: "Избыточно: эти модификаторы слёз у вас уже есть.", pl: "Nadmiarowe: masz już te modyfikatory łez.", zh: "冗余：这些眼泪修饰你已经有了。", ja: "重複：その涙修飾はすでに持っている。", hi: "अनावश्यक: ये आँसू-संशोधक आपके पास पहले से हैं।", ar: "تكرار: لديك بالفعل معدّلات الدموع هذه.", bn: "অপ্রয়োজনীয়: এই অশ্রু-পরিবর্তকগুলো আপনার আগেই আছে।", ur: "غیر ضروری: یہ آنسو موڈیفائرز آپ کے پاس پہلے سے ہیں۔" },
  "bldn.v_situational": { en: "Situational pick: stat gains, but no strong named synergy.", fr: "Choix situationnel : des gains de stats, mais aucune synergie nommée forte.", es: "Elección situacional: sube estadísticas, pero sin sinergia nombrada fuerte.", pt: "Escolha situacional: ganho de atributos, mas nenhuma sinergia nomeada forte.", de: "Situative Wahl: Werte steigen, aber keine starke benannte Synergie.", ru: "Ситуативный выбор: прирост характеристик, но сильной именованной синергии нет.", pl: "Wybór sytuacyjny: przyrost statystyk, ale brak silnej nazwanej synergii.", zh: "视情况而定：属性有提升，但没有明确的强力联动。", ja: "状況次第：ステータスは伸びるが、名の付いた強シナジーはない。", hi: "परिस्थिति पर निर्भर: स्टैट बढ़ते हैं, पर कोई मज़बूत नामित तालमेल नहीं।", ar: "اختيار ظرفي: زيادة في الإحصاءات، لكن دون تآزر قوي موثّق.", bn: "পরিস্থিতিনির্ভর: স্ট্যাট বাড়ে, তবে শক্তিশালী নামধারী সমন্বয় নেই।", ur: "حالات پر منحصر: اسٹیٹس بڑھتے ہیں، مگر کوئی مضبوط نامزد ہم آہنگی نہیں۔" },

  // ═══ Build assistant - character picker ═══
  "bld.character": { en: "Character", fr: "Personnage", es: "Personaje", pt: "Personagem", de: "Figur", ru: "Персонаж", pl: "Postać", zh: "角色", ja: "キャラクター", hi: "किरदार", ar: "الشخصية", bn: "চরিত্র", ur: "کردار" },
  "bld.noCharacter": { en: "No character", fr: "Aucun personnage", es: "Sin personaje", pt: "Sem personagem", de: "Keine Figur", ru: "Без персонажа", pl: "Bez postaci", zh: "未选角色", ja: "キャラクターなし", hi: "कोई किरदार नहीं", ar: "بدون شخصية", bn: "কোনো চরিত্র নয়", ur: "کوئی کردار نہیں" },
  "bld.characterHint": { en: "Some characters fly or fire modified tears with no item at all — The Lost, for one. Pick yours and the analysis stops guessing.", fr: "Certains personnages volent ou tirent des larmes modifiées sans le moindre objet — The Lost, par exemple. Choisis le tien et l'analyse arrête de deviner.", es: "Algunos personajes vuelan o disparan lágrimas modificadas sin ningún objeto — The Lost, por ejemplo. Elige el tuyo y el análisis dejará de suponer.", pt: "Alguns personagens voam ou atiram lágrimas modificadas sem item algum — The Lost, por exemplo. Escolha o seu e a análise para de adivinhar.", de: "Manche Figuren fliegen oder schießen veränderte Tränen ganz ohne Gegenstand — The Lost etwa. Wähle deine, und die Analyse rät nicht mehr.", ru: "Некоторые персонажи летают или стреляют изменёнными слезами вообще без предметов — например, The Lost. Выберите своего, и анализ перестанет гадать.", pl: "Niektóre postacie latają lub strzelają zmodyfikowanymi łzami bez żadnego przedmiotu — choćby The Lost. Wybierz swoją, a analiza przestanie zgadywać.", zh: "有些角色不需要任何道具就能飞行或发射特殊眼泪——比如 The Lost。选好角色，分析就不用靠猜。", ja: "アイテムなしで飛行や特殊な涙を持つキャラクターがいる — 例えば The Lost。自分のキャラを選べば、分析は推測をやめる。", hi: "कुछ किरदार बिना किसी वस्तु के उड़ते हैं या बदले हुए आँसू दागते हैं — जैसे The Lost। अपना किरदार चुनें और विश्लेषण अनुमान लगाना बंद कर देगा।", ar: "بعض الشخصيات تطير أو تطلق دموعًا معدّلة دون أي غرض — مثل The Lost. اختر شخصيتك ليتوقف التحليل عن التخمين.", bn: "কিছু চরিত্র কোনো আইটেম ছাড়াই ওড়ে বা পরিবর্তিত অশ্রু ছোড়ে — যেমন The Lost। নিজেরটি বেছে নিন, বিশ্লেষণ আর আন্দাজ করবে না।", ur: "کچھ کردار بغیر کسی آئٹم کے اڑتے یا بدلے ہوئے آنسو داغتے ہیں — جیسے The Lost۔ اپنا کردار منتخب کریں، تجزیہ اندازہ لگانا چھوڑ دے گا۔" },
  // ═══ Companion mod - version drift ═══
  "mod.updateTitle": { en: "The stats mod needs updating", fr: "Le mod de stats doit être mis à jour", es: "El mod de estadísticas necesita actualizarse", pt: "O mod de estatísticas precisa ser atualizado", de: "Die Statistik-Mod muss aktualisiert werden", ru: "Мод статистики нужно обновить", pl: "Mod statystyk wymaga aktualizacji", zh: "统计模组需要更新", ja: "統計 Mod の更新が必要です", hi: "स्टैट्स मॉड को अपडेट करना है", ar: "مود الإحصاءات بحاجة إلى تحديث", bn: "স্ট্যাটস মড আপডেট করা দরকার", ur: "اسٹیٹس ماڈ کو اپ ڈیٹ کرنا ہے" },
  "mod.updateBody": { en: "Isaac is loading v{installed}, but this app ships v{bundled}. Reinstall it, then restart Isaac — mods are only loaded at game startup. Your run history is kept.", fr: "Isaac charge la v{installed}, alors que cette app fournit la v{bundled}. Réinstalle-le, puis relance Isaac — les mods ne sont chargés qu'au démarrage du jeu. Ton historique de runs est conservé.", es: "Isaac carga la v{installed}, pero esta app trae la v{bundled}. Reinstálalo y reinicia Isaac — los mods solo se cargan al arrancar el juego. Tu historial de runs se conserva.", pt: "O Isaac carrega a v{installed}, mas este app traz a v{bundled}. Reinstale-o e reinicie o Isaac — mods só são carregados na inicialização do jogo. Seu histórico de runs é mantido.", de: "Isaac lädt v{installed}, diese App liefert aber v{bundled}. Installiere sie neu und starte Isaac neu — Mods werden nur beim Spielstart geladen. Dein Run-Verlauf bleibt erhalten.", ru: "Isaac загружает v{installed}, а это приложение поставляет v{bundled}. Переустановите мод и перезапустите Isaac — моды загружаются только при старте игры. История забегов сохраняется.", pl: "Isaac ładuje v{installed}, a ta aplikacja dostarcza v{bundled}. Zainstaluj go ponownie i uruchom Isaaca — mody wczytują się tylko przy starcie gry. Historia runów zostaje zachowana.", zh: "Isaac 加载的是 v{installed}，而本应用附带 v{bundled}。请重新安装并重启 Isaac——模组只在游戏启动时加载。你的运行历史会保留。", ja: "Isaac は v{installed} を読み込んでいますが、このアプリは v{bundled} を同梱しています。再インストールして Isaac を再起動してください — Mod はゲーム起動時にのみ読み込まれます。ラン履歴は保持されます。", hi: "Isaac v{installed} लोड कर रहा है, पर यह ऐप v{bundled} देता है। इसे फिर से इंस्टॉल करें और Isaac पुनः चालू करें — मॉड केवल गेम शुरू होने पर लोड होते हैं। आपका रन इतिहास बना रहता है।", ar: "يحمّل Isaac الإصدار v{installed}، بينما يوفّر هذا التطبيق v{bundled}. أعد تثبيته ثم أعد تشغيل Isaac — فالمودات لا تُحمَّل إلا عند بدء اللعبة. سجل جولاتك محفوظ.", bn: "Isaac v{installed} লোড করছে, কিন্তু এই অ্যাপ v{bundled} সরবরাহ করে। পুনরায় ইনস্টল করে Isaac চালু করুন — মড কেবল গেম চালুর সময় লোড হয়। আপনার রান ইতিহাস অক্ষত থাকে।", ur: "Isaac v{installed} لوڈ کر رہا ہے، جبکہ یہ ایپ v{bundled} فراہم کرتی ہے۔ دوبارہ انسٹال کریں اور Isaac ری اسٹارٹ کریں — ماڈز صرف گیم اسٹارٹ پر لوڈ ہوتے ہیں۔ آپ کی رن ہسٹری محفوظ رہتی ہے۔" },
  "mod.updateBtn": { en: "Update the mod", fr: "Mettre à jour le mod", es: "Actualizar el mod", pt: "Atualizar o mod", de: "Mod aktualisieren", ru: "Обновить мод", pl: "Zaktualizuj mod", zh: "更新模组", ja: "Mod を更新", hi: "मॉड अपडेट करें", ar: "تحديث المود", bn: "মড আপডেট করুন", ur: "ماڈ اپ ڈیٹ کریں" },

  "bld.quality": { en: "Item quality (0-4)", fr: "Qualité de l'objet (0-4)", es: "Calidad del objeto (0-4)", pt: "Qualidade do item (0-4)", de: "Gegenstandsqualität (0-4)", ru: "Качество предмета (0-4)", pl: "Jakość przedmiotu (0-4)", zh: "道具品质（0-4）", ja: "アイテム品質 (0-4)", hi: "वस्तु गुणवत्ता (0-4)", ar: "جودة الغرض (0-4)", bn: "আইটেম মান (0-4)", ur: "آئٹم کوالٹی (0-4)" },

  "slot.n": { en: "Slot {n}", fr: "Emplacement {n}", es: "Ranura {n}", pt: "Slot {n}", de: "Slot {n}", ru: "Слот {n}", pl: "Slot {n}", zh: "存档位 {n}", ja: "スロット {n}", hi: "स्लॉट {n}", ar: "الخانة {n}", bn: "স্লট {n}", ur: "سلاٹ {n}" },
  "bld.familiarShort": { en: "familiar", fr: "familier", es: "familiar", pt: "familiar", de: "Begleiter", ru: "спутник", pl: "chowaniec", zh: "跟班", ja: "使い魔", hi: "फ़ैमिलियर", ar: "تابع", bn: "ফ্যামিলিয়ার", ur: "فیملیئر" },
  "bld.familiarFlagTitle": { en: "Carried by a familiar: its tears, not yours.", fr: "Porté par un familier : ses larmes, pas les tiennes.", es: "Lo lleva un familiar: sus lágrimas, no las tuyas.", pt: "Vem de um familiar: as lágrimas dele, não as suas.", de: "Kommt von einem Begleiter: seine Tränen, nicht deine.", ru: "От спутника: его слёзы, не ваши.", pl: "Od chowańca: jego łzy, nie twoje.", zh: "来自跟班：是它的眼泪，不是你的。", ja: "使い魔によるもの：その涙であって、あなたの涙ではない。", hi: "फ़ैमिलियर से: उसके आँसू, आपके नहीं।", ar: "من تابع: دموعه هو، لا دموعك.", bn: "ফ্যামিলিয়ার থেকে: তার অশ্রু, আপনার নয়।", ur: "فیملیئر سے: اس کے آنسو، آپ کے نہیں۔" },
  "bld.runInProgress": { en: "in progress", fr: "en cours", es: "en curso", pt: "em andamento", de: "läuft", ru: "в процессе", pl: "w toku", zh: "进行中", ja: "進行中", hi: "जारी", ar: "جارية", bn: "চলমান", ur: "جاری" },
};
