// SPDX-License-Identifier: GPL-3.0-only
// Isaac Completion Tracker — © 2026 reiassezbeau — https://github.com/reiassezbeau

/**
 * i18n-views — textes des VUES dans les 13 langues (le chrome est dans i18n.ts).
 * Repli : langue demandée -> anglais -> clé. Traductions perfectibles pour les
 * langues non-latines : corrections communautaires bienvenues (open-source).
 */
import type { Lang } from "./i18n";

type Entry = Partial<Record<Lang, string>>;

export const VIEW_STRINGS: Record<string, Entry> = {
  // ═══ Dashboard ═══
  "dash.distanceDeadGod": { en: "Distance to Dead God", fr: "Distance à Dead God", es: "Distancia a Dead God", pt: "Distância até Dead God", de: "Entfernung zu Dead God", ru: "До Dead God", pl: "Dystans do Dead God", zh: "距离 Dead God", ja: "Dead God まで", hi: "Dead God तक की दूरी", ar: "المسافة إلى Dead God", bn: "Dead God পর্যন্ত দূরত্ব", ur: "Dead God تک فاصلہ" },
  "dash.remaining": { en: "remaining", fr: "restantes", es: "restantes", pt: "restantes", de: "verbleibend", ru: "осталось", pl: "pozostało", zh: "剩余", ja: "残り", hi: "शेष", ar: "متبقٍ", bn: "বাকি", ur: "باقی" },
  "dash.hardMarks": { en: "Hard marks", fr: "marks Hard", es: "marcas Hard", pt: "marcas Hard", de: "Hard-Marken", ru: "метки Hard", pl: "znaczniki Hard", zh: "Hard 标记", ja: "Hard マーク", hi: "Hard मार्क", ar: "علامات Hard", bn: "Hard মার্ক", ur: "Hard مارکس" },
  "dash.ringsHint": { en: "12 rings = the 12 endings · center → outside = Mom's Heart → The Beast", fr: "12 anneaux = les 12 endings · centre → extérieur = Mom's Heart → The Beast", es: "12 anillos = los 12 finales · centro → exterior = Mom's Heart → The Beast", pt: "12 anéis = os 12 finais · centro → fora = Mom's Heart → The Beast", de: "12 Ringe = die 12 Endings · Mitte → außen = Mom's Heart → The Beast", ru: "12 колец = 12 концовок · центр → край = Mom's Heart → The Beast", pl: "12 pierścieni = 12 zakończeń · środek → zewnątrz = Mom's Heart → The Beast", zh: "12 个环 = 12 个结局 · 由内向外 = Mom's Heart → The Beast", ja: "12のリング＝12のエンディング・中心→外＝Mom's Heart → The Beast", hi: "12 वलय = 12 एंडिंग · केंद्र → बाहर = Mom's Heart → The Beast", ar: "١٢ حلقة = النهايات الـ١٢ · من المركز إلى الخارج = Mom's Heart → The Beast", bn: "১২টি রিং = ১২টি এন্ডিং · কেন্দ্র → বাইরে = Mom's Heart → The Beast", ur: "12 حلقے = 12 اینڈنگز · مرکز → باہر = Mom's Heart → The Beast" },
  "dash.unlockedAch": { en: "Achievements unlocked", fr: "Succès débloqués", es: "Logros desbloqueados", pt: "Conquistas desbloqueadas", de: "Freigeschaltete Erfolge", ru: "Открытые достижения", pl: "Odblokowane osiągnięcia", zh: "已解锁成就", ja: "解除した実績", hi: "अनलॉक उपलब्धियाँ", ar: "الإنجازات المفتوحة", bn: "আনলক করা অর্জন", ur: "کھلے کارنامے" },
  "dash.left": { en: "left", fr: "restants", es: "restantes", pt: "restantes", de: "übrig", ru: "осталось", pl: "pozostało", zh: "剩余", ja: "残り", hi: "शेष", ar: "متبقٍ", bn: "বাকি", ur: "باقی" },
  "dash.normalMarks": { en: "Normal marks", fr: "Marks Normal", es: "Marcas Normal", pt: "Marcas Normal", de: "Normal-Marken", ru: "Метки Normal", pl: "Znaczniki Normal", zh: "Normal 标记", ja: "Normal マーク", hi: "Normal मार्क", ar: "علامات Normal", bn: "Normal মার্ক", ur: "Normal مارکس" },
  "dash.toRedo": { en: "to redo", fr: "à refaire", es: "por rehacer", pt: "a refazer", de: "zu wiederholen", ru: "переделать", pl: "do powtórki", zh: "需重做", ja: "やり直し", hi: "फिर से करें", ar: "لإعادتها", bn: "পুনরায় করতে", ur: "دوبارہ کرنے کو" },
  "dash.fullChars": { en: "Characters done", fr: "Persos bouclés", es: "Personajes completos", pt: "Personagens completos", de: "Fertige Charaktere", ru: "Готовые персонажи", pl: "Ukończone postacie", zh: "完成的角色", ja: "完了キャラ", hi: "पूर्ण पात्र", ar: "شخصيات مكتملة", bn: "সম্পূর্ণ চরিত্র", ur: "مکمل کردار" },
  "dash.byCategory": { en: "Breakdown by category", fr: "Répartition par catégorie", es: "Desglose por categoría", pt: "Divisão por categoria", de: "Aufteilung nach Kategorie", ru: "Разбивка по категориям", pl: "Podział na kategorie", zh: "按类别划分", ja: "カテゴリ別内訳", hi: "श्रेणी अनुसार विभाजन", ar: "التوزيع حسب الفئة", bn: "বিভাগ অনুযায়ী বিভাজন", ur: "زمرے کے مطابق تقسیم" },
  "dash.unlockedTotal": { en: "unlocked / total", fr: "débloqués / total", es: "desbloqueados / total", pt: "desbloqueadas / total", de: "freigeschaltet / gesamt", ru: "открыто / всего", pl: "odblokowane / razem", zh: "已解锁 / 总数", ja: "解除 / 全体", hi: "अनलॉक / कुल", ar: "مفتوح / الإجمالي", bn: "আনলক / মোট", ur: "کھلے / کل" },
  "dash.nextTargets": { en: "Recommended next targets", fr: "Prochaines cibles recommandées", es: "Próximos objetivos recomendados", pt: "Próximos alvos recomendados", de: "Empfohlene nächste Ziele", ru: "Рекомендуемые цели", pl: "Zalecane następne cele", zh: "推荐的下一个目标", ja: "次のおすすめ目標", hi: "अगले सुझाए लक्ष्य", ar: "الأهداف التالية المقترحة", bn: "পরবর্তী প্রস্তাবিত লক্ষ্য", ur: "اگلے تجویز کردہ اہداف" },
  "dash.fromSave": { en: "computed from your save", fr: "calculé depuis ta save", es: "calculado desde tu partida", pt: "calculado do seu save", de: "aus deinem Spielstand berechnet", ru: "рассчитано по сохранению", pl: "obliczone z zapisu", zh: "根据你的存档计算", ja: "セーブから計算", hi: "आपके सेव से गणना", ar: "محسوب من ملف الحفظ", bn: "আপনার সেভ থেকে গণনা", ur: "آپ کے سیو سے شمار" },
  "dash.allDone": { en: "All done on this side 🎉", fr: "Tout est bouclé de ce côté 🎉", es: "Todo listo por aquí 🎉", pt: "Tudo concluído por aqui 🎉", de: "Hier ist alles erledigt 🎉", ru: "Здесь всё готово 🎉", pl: "Tutaj wszystko zrobione 🎉", zh: "这边全部完成 🎉", ja: "こちらは全部完了 🎉", hi: "इस ओर सब पूरा 🎉", ar: "كل شيء مكتمل هنا 🎉", bn: "এদিকে সব সম্পন্ন 🎉", ur: "یہاں سب مکمل 🎉" },
  "dash.newAch": { en: "achievements", fr: "succès", es: "logros", pt: "conquistas", de: "Erfolge", ru: "достижений", pl: "osiągnięć", zh: "成就", ja: "実績", hi: "उपलब्धियाँ", ar: "إنجازات", bn: "অর্জন", ur: "کارنامے" },
  "dash.hardMark": { en: "Hard mark", fr: "mark Hard", es: "marca Hard", pt: "marca Hard", de: "Hard-Marke", ru: "метка Hard", pl: "znacznik Hard", zh: "Hard 标记", ja: "Hard マーク", hi: "Hard मार्क", ar: "علامة Hard", bn: "Hard মার্ক", ur: "Hard مارک" },
  "dash.marksUnreliable": { en: "Completion marks unreliable", fr: "Completion marks non fiables", es: "Marcas de completado no fiables", pt: "Marcas de conclusão não confiáveis", de: "Completion Marks unzuverlässig", ru: "Метки завершения ненадёжны", pl: "Znaczniki ukończenia niewiarygodne", zh: "完成标记不可靠", ja: "コンプリートマークが不確実", hi: "कम्प्लीशन मार्क अविश्वसनीय", ar: "علامات الإكمال غير موثوقة", bn: "কমপ্লিশন মার্ক অনির্ভরযোগ্য", ur: "کمپلیشن مارکس ناقابل اعتبار" },
  "dash.marksUnreliableBody": { en: "for this save (unexpected format). Decoding was disabled to avoid showing wrong data — use the", fr: "pour cette sauvegarde (format inattendu). Le décodage a été désactivé pour éviter d'afficher des données fausses — utilise les", es: "para esta partida (formato inesperado). La decodificación se desactivó para no mostrar datos falsos — usa las", pt: "para este save (formato inesperado). A decodificação foi desativada para não exibir dados errados — use as", de: "für diesen Spielstand (unerwartetes Format). Die Dekodierung wurde deaktiviert, um keine falschen Daten zu zeigen — nutze die", ru: "для этого сохранения (неожиданный формат). Декодирование отключено, чтобы не показывать неверные данные — используйте", pl: "dla tego zapisu (nieoczekiwany format). Dekodowanie wyłączono, by nie pokazywać błędnych danych — użyj", zh: "此存档（格式异常）。已停用解码以免显示错误数据——请使用", ja: "このセーブでは（想定外の形式）。誤ったデータ表示を避けるため解読を無効化しました —", hi: "इस सेव के लिए (अप्रत्याशित प्रारूप)। गलत डेटा दिखाने से बचने हेतु डिकोडिंग बंद — उपयोग करें", ar: "لملف الحفظ هذا (تنسيق غير متوقع). عُطِّل فك الترميز لتجنّب عرض بيانات خاطئة — استخدم", bn: "এই সেভের জন্য (অপ্রত্যাশিত ফরম্যাট)। ভুল ডেটা এড়াতে ডিকোডিং বন্ধ — ব্যবহার করুন", ur: "اس سیو کے لیے (غیر متوقع فارمیٹ)۔ غلط ڈیٹا سے بچنے کو ڈیکوڈنگ بند — استعمال کریں" },
  "dash.manualOverrides": { en: "manual overrides", fr: "corrections manuelles", es: "correcciones manuales", pt: "correções manuais", de: "manuelle Korrekturen", ru: "ручные правки", pl: "ręczne korekty", zh: "手动修正", ja: "手動修正", hi: "मैन्युअल सुधार", ar: "التصحيحات اليدوية", bn: "ম্যানুয়াল সংশোধন", ur: "دستی درستیاں" },
  "dash.checksumWarn": { en: "⚠ The save checksum doesn't match (file may be mid-write). Data is still readable; refresh if needed.", fr: "⚠ Le checksum de la sauvegarde ne correspond pas (fichier peut-être en cours d'écriture). Les données restent lisibles ; rafraîchis si besoin.", es: "⚠ La suma de verificación no coincide (el archivo puede estar escribiéndose). Los datos siguen legibles; actualiza si hace falta.", pt: "⚠ O checksum do save não confere (arquivo talvez em gravação). Os dados continuam legíveis; atualize se preciso.", de: "⚠ Die Prüfsumme stimmt nicht (Datei wird evtl. gerade geschrieben). Daten bleiben lesbar; ggf. aktualisieren.", ru: "⚠ Контрольная сумма не совпадает (файл может записываться). Данные читаемы; обновите при необходимости.", pl: "⚠ Suma kontrolna się nie zgadza (plik może być zapisywany). Dane są czytelne; odśwież w razie potrzeby.", zh: "⚠ 存档校验和不匹配（文件可能正在写入）。数据仍可读；需要时请刷新。", ja: "⚠ セーブのチェックサムが不一致（書き込み中の可能性）。データは読めます。必要なら更新を。", hi: "⚠ सेव चेकसम मेल नहीं खाता (फ़ाइल लिखी जा रही हो सकती है)। डेटा पठनीय है; ज़रूरत हो तो ताज़ा करें।", ar: "⚠ المجموع الاختباري غير مطابق (قد يكون الملف قيد الكتابة). البيانات مقروءة؛ حدِّث عند الحاجة.", bn: "⚠ সেভ চেকসাম মেলেনি (ফাইল লেখা হচ্ছে হয়তো)। ডেটা পাঠযোগ্য; দরকারে রিফ্রেশ করুন।", ur: "⚠ سیو چیک سم میل نہیں کھاتا (فائل لکھی جا رہی ہو سکتی ہے)۔ ڈیٹا پڑھنے کے قابل ہے؛ ضرورت ہو تو ریفریش کریں۔" },

  // ═══ La Grille ═══
  "grid.subtitle": { en: "34 characters × 12 marks", fr: "Les 34 personnages × 12 marques", es: "34 personajes × 12 marcas", pt: "34 personagens × 12 marcas", de: "34 Charaktere × 12 Marken", ru: "34 персонажа × 12 меток", pl: "34 postacie × 12 znaczników", zh: "34 个角色 × 12 个标记", ja: "34キャラ × 12マーク", hi: "34 पात्र × 12 मार्क", ar: "٣٤ شخصية × ١٢ علامة", bn: "৩৪ চরিত্র × ১২ মার্ক", ur: "34 کردار × 12 مارکس" },
  "grid.legendHint": { en: "gold = Hard, green ring = Normal (redo), hollow = to do. Column totals show the bottleneck at a glance.", fr: "Or = Hard, anneau vert = Normal (à refaire), creux = à faire. Les totaux de colonne montrent le goulot d'un coup d'œil.", es: "Oro = Hard, anillo verde = Normal (rehacer), hueco = pendiente. Los totales por columna muestran el cuello de botella.", pt: "Ouro = Hard, anel verde = Normal (refazer), vazado = a fazer. Os totais por coluna mostram o gargalo.", de: "Gold = Hard, grüner Ring = Normal (wiederholen), hohl = offen. Spaltensummen zeigen den Engpass.", ru: "Золото = Hard, зелёное кольцо = Normal (переделать), пусто = не сделано. Итоги столбцов показывают узкое место.", pl: "Złoto = Hard, zielony pierścień = Normal (powtórka), puste = do zrobienia. Sumy kolumn pokazują wąskie gardło.", zh: "金色 = Hard，绿环 = Normal（需重做），空心 = 待完成。列合计一眼看出瓶颈。", ja: "金 = Hard、緑の輪 = Normal（やり直し）、空 = 未完了。列の合計でボトルネックが一目で分かります。", hi: "सुनहरा = Hard, हरा वलय = Normal (फिर से), खोखला = बाकी। कॉलम योग बाधा दिखाते हैं।", ar: "ذهبي = Hard، حلقة خضراء = Normal (إعادة)، مجوّف = متبقٍ. مجاميع الأعمدة تُظهر الاختناق.", bn: "সোনালি = Hard, সবুজ রিং = Normal (পুনরায়), ফাঁপা = বাকি। কলাম যোগফল বাধা দেখায়।", ur: "سنہری = Hard، سبز حلقہ = Normal (دوبارہ)، خالی = باقی۔ کالم کے مجموعے رکاوٹ دکھاتے ہیں۔" },
  "grid.hoverHint": { en: "· hover a cell = character · ending · status", fr: "· survol d'une cellule = perso · ending · statut", es: "· pasa el ratón = personaje · final · estado", pt: "· passe o mouse = personagem · final · status", de: "· Zelle überfahren = Charakter · Ending · Status", ru: "· наведение = персонаж · концовка · статус", pl: "· najedź = postać · zakończenie · status", zh: "· 悬停单元格 = 角色 · 结局 · 状态", ja: "· セルにホバー = キャラ · エンディング · 状態", hi: "· सेल पर होवर = पात्र · एंडिंग · स्थिति", ar: "· مرِّر فوق خلية = شخصية · نهاية · حالة", bn: "· সেলে হোভার = চরিত্র · এন্ডিং · অবস্থা", ur: "· سیل پر ہوور = کردار · اینڈنگ · حالت" },
  "grid.characters": { en: "Characters", fr: "Personnages", es: "Personajes", pt: "Personagens", de: "Charaktere", ru: "Персонажи", pl: "Postacie", zh: "角色", ja: "キャラクター", hi: "पात्र", ar: "الشخصيات", bn: "চরিত্র", ur: "کردار" },
  "grid.perCol": { en: "Hard / col", fr: "Hard / col", es: "Hard / col", pt: "Hard / col", de: "Hard / Sp.", ru: "Hard / стлб", pl: "Hard / kol.", zh: "Hard / 列", ja: "Hard / 列", hi: "Hard / कॉलम", ar: "Hard / عمود", bn: "Hard / কলাম", ur: "Hard / کالم" },
  // « Hard » et « Normal » sont les termes DU JEU : volontairement non traduits
  // (fidelite a Isaac — les joueurs les utilisent tels quels dans toutes les langues).
  "mark.hard": { en: "Hard", fr: "Hard" },
  "mark.normal": { en: "Normal", fr: "Normal" },
  "mark.todo": { en: "To do", fr: "À faire", es: "Pendiente", pt: "A fazer", de: "Offen", ru: "Не сделано", pl: "Do zrobienia", zh: "待完成", ja: "未完了", hi: "बाकी", ar: "متبقٍ", bn: "বাকি", ur: "باقی" },

  // ═══ Personnage ═══
  "char.locked": { en: "Character locked", fr: "Perso verrouillé", es: "Personaje bloqueado", pt: "Personagem bloqueado", de: "Charakter gesperrt", ru: "Персонаж закрыт", pl: "Postać zablokowana", zh: "角色未解锁", ja: "キャラ未解除", hi: "पात्र लॉक", ar: "الشخصية مقفلة", bn: "চরিত্র লক", ur: "کردار مقفل" },
  "char.regular": { en: "Regular", fr: "Régulier", es: "Normal", pt: "Regular", de: "Regulär", ru: "Обычный", pl: "Zwykła", zh: "普通", ja: "通常", hi: "सामान्य", ar: "عادي", bn: "সাধারণ", ur: "عام" },
  "char.gameStats": { en: "Game stats (this character)", fr: "Stats de jeu (ce perso)", es: "Estadísticas (este personaje)", pt: "Estatísticas (este personagem)", de: "Spielstatistik (dieser Charakter)", ru: "Игровая статистика (персонаж)", pl: "Statystyki gry (ta postać)", zh: "游戏统计（该角色）", ja: "ゲーム統計（このキャラ）", hi: "गेम आँकड़े (यह पात्र)", ar: "إحصاءات اللعب (هذه الشخصية)", bn: "গেম পরিসংখ্যান (এই চরিত্র)", ur: "گیم شماریات (یہ کردار)" },
  "char.fromMod": { en: "from the stats mod", fr: "depuis le mod de stats", es: "desde el mod de estadísticas", pt: "do mod de estatísticas", de: "aus dem Statistik-Mod", ru: "из мода статистики", pl: "z moda statystyk", zh: "来自统计 mod", ja: "統計 mod から", hi: "स्टैट्स मॉड से", ar: "من مود الإحصاءات", bn: "স্ট্যাটস মড থেকে", ur: "اسٹیٹس ماڈ سے" },
  "char.runs": { en: "Runs", fr: "Runs", es: "Partidas", pt: "Runs", de: "Runs", ru: "Забеги", pl: "Runy", zh: "局数", ja: "ラン数", hi: "रन", ar: "الجولات", bn: "রান", ur: "رنز" },
  "char.winrate": { en: "Winrate", fr: "Winrate", es: "Victorias", pt: "Vitórias", de: "Siegrate", ru: "Победы", pl: "Wygrane", zh: "胜率", ja: "勝率", hi: "जीत दर", ar: "نسبة الفوز", bn: "জয়ের হার", ur: "جیت کی شرح" },
  "char.hitsPerRun": { en: "Hits / run", fr: "Hits / run", es: "Golpes / partida", pt: "Hits / run", de: "Treffer / Run", ru: "Урон / забег", pl: "Trafienia / run", zh: "每局受击", ja: "被弾 / ラン", hi: "हिट / रन", ar: "إصابات / جولة", bn: "হিট / রান", ur: "ہٹس / رن" },
  "char.record": { en: "Record (min hits)", fr: "Record (min hits)", es: "Récord (mín. golpes)", pt: "Recorde (mín. hits)", de: "Rekord (min. Treffer)", ru: "Рекорд (мин. урон)", pl: "Rekord (min. trafień)", zh: "记录（最少受击）", ja: "記録（最少被弾）", hi: "रिकॉर्ड (न्यून. हिट)", ar: "الرقم القياسي (أقل إصابات)", bn: "রেকর্ড (সর্বনিম্ন হিট)", ur: "ریکارڈ (کم ترین ہٹس)" },
  "char.marksLegend": { en: "green = Normal · gold = Hard", fr: "vert = Normal · or = Hard", es: "verde = Normal · oro = Hard", pt: "verde = Normal · ouro = Hard", de: "grün = Normal · gold = Hard", ru: "зелёный = Normal · золото = Hard", pl: "zielony = Normal · złoto = Hard", zh: "绿色 = Normal · 金色 = Hard", ja: "緑 = Normal · 金 = Hard", hi: "हरा = Normal · सुनहरा = Hard", ar: "أخضر = Normal · ذهبي = Hard", bn: "সবুজ = Normal · সোনালি = Hard", ur: "سبز = Normal · سنہری = Hard" },
  "char.completionMarks": { en: "Completion marks", fr: "Completion marks", es: "Marcas de completado", pt: "Marcas de conclusão", de: "Completion Marks", ru: "Метки завершения", pl: "Znaczniki ukończenia", zh: "完成标记", ja: "コンプリートマーク", hi: "कम्प्लीशन मार्क", ar: "علامات الإكمال", bn: "কমপ্লিশন মার্ক", ur: "کمپلیشن مارکس" },
  "char.todoTitle": { en: "What's left to do", fr: "Ce qu'il te reste à faire", es: "Lo que te queda por hacer", pt: "O que falta fazer", de: "Was noch zu tun ist", ru: "Что осталось сделать", pl: "Co zostało do zrobienia", zh: "还需要做什么", ja: "残っていること", hi: "अभी क्या बाकी है", ar: "ما تبقّى لك", bn: "যা করা বাকি", ur: "کیا باقی ہے" },
  "char.allHard": { en: "Everything is Hard for this character 🎉", fr: "Tout est en Hard pour ce perso 🎉", es: "Todo en Hard para este personaje 🎉", pt: "Tudo em Hard para este personagem 🎉", de: "Alles auf Hard für diesen Charakter 🎉", ru: "Всё на Hard для этого персонажа 🎉", pl: "Wszystko na Hard dla tej postaci 🎉", zh: "该角色全部 Hard 完成 🎉", ja: "このキャラは全て Hard 達成 🎉", hi: "इस पात्र के लिए सब Hard 🎉", ar: "كل شيء Hard لهذه الشخصية 🎉", bn: "এই চরিত্রের সব Hard 🎉", ur: "اس کردار کے لیے سب Hard 🎉" },
  "char.redoHard": { en: "Redo on Hard (gold mark)", fr: "Refaire en Hard (marque dorée)", es: "Rehacer en Hard (marca dorada)", pt: "Refazer no Hard (marca dourada)", de: "Auf Hard wiederholen (goldene Marke)", ru: "Переделать на Hard (золотая метка)", pl: "Powtórz na Hard (złoty znacznik)", zh: "以 Hard 重做（金色标记）", ja: "Hard でやり直し（金マーク）", hi: "Hard में फिर से (सुनहरा मार्क)", ar: "أعِدها على Hard (علامة ذهبية)", bn: "Hard-এ পুনরায় (সোনালি মার্ক)", ur: "Hard پر دوبارہ (سنہری مارک)" },
  "char.markToGet": { en: "Mark to obtain", fr: "Marque à obtenir", es: "Marca por obtener", pt: "Marca a obter", de: "Zu erhaltende Marke", ru: "Метка к получению", pl: "Znacznik do zdobycia", zh: "待获得的标记", ja: "獲得すべきマーク", hi: "प्राप्त करने योग्य मार्क", ar: "علامة لتحصيلها", bn: "অর্জনযোগ্য মার্ক", ur: "حاصل کرنے کا مارک" },
  "char.routingTips": { en: "Routing tips", fr: "Conseils de routing", es: "Consejos de ruta", pt: "Dicas de rota", de: "Routing-Tipps", ru: "Советы по маршруту", pl: "Wskazówki trasy", zh: "路线建议", ja: "ルート指南", hi: "रूटिंग सुझाव", ar: "نصائح المسار", bn: "রুটিং পরামর্শ", ur: "روٹنگ تجاویز" },
  "char.select": { en: "Select a character.", fr: "Sélectionne un personnage.", es: "Selecciona un personaje.", pt: "Selecione um personagem.", de: "Wähle einen Charakter.", ru: "Выберите персонажа.", pl: "Wybierz postać.", zh: "选择一个角色。", ja: "キャラクターを選択。", hi: "एक पात्र चुनें।", ar: "اختر شخصية.", bn: "একটি চরিত্র বেছে নিন।", ur: "ایک کردار منتخب کریں۔" },
  "char.marksUnreliable": { en: "Marks unreliable for this save — fix them manually in ⚙️ Overrides.", fr: "Marks non fiables pour cette save — corrige-les manuellement dans ⚙️ Corrections.", es: "Marcas no fiables para esta partida — corrígelas en ⚙️ Correcciones.", pt: "Marcas não confiáveis neste save — corrija em ⚙️ Correções.", de: "Marken für diesen Spielstand unzuverlässig — korrigiere sie in ⚙️ Korrekturen.", ru: "Метки ненадёжны для этого сохранения — исправьте в ⚙️ Правки.", pl: "Znaczniki niewiarygodne dla tego zapisu — popraw w ⚙️ Korekty.", zh: "该存档标记不可靠——请在 ⚙️ 手动修正 中更正。", ja: "このセーブではマークが不確実 — ⚙️ 修正 で手動調整を。", hi: "इस सेव के मार्क अविश्वसनीय — ⚙️ सुधार में ठीक करें।", ar: "العلامات غير موثوقة لهذا الحفظ — صحّحها في ⚙️ التصحيحات.", bn: "এই সেভে মার্ক অনির্ভরযোগ্য — ⚙️ সংশোধন-এ ঠিক করুন।", ur: "اس سیو کے مارکس ناقابل اعتبار — ⚙️ درستیاں میں درست کریں۔" },
};
