// SPDX-License-Identifier: GPL-3.0-only
// Isaac Completion Tracker — © 2026 reiassezbeau — https://github.com/reiassezbeau

/**
 * i18n - view strings (4/4): the strings that used to be hardcoded in the
 * components, plus the shared domain vocabulary used by `lib/format.ts`
 * (categories, item roles, tear flags, stat dimensions, synergy verdicts).
 * Fallback: requested language -> English -> key. Translations are imperfect for
 * the non-Latin languages: community fixes are welcome (open-source).
 *
 * NOT translated on purpose (faithfulness to Isaac - players use the English
 * terms in every language): floor names, DLC names, "Hard" / "Normal",
 * and the theme names (Basement, Sheol, The Void, Corpse, Cathedral).
 */
import type { Lang } from "./i18n";

type Entry = Partial<Record<Lang, string>>;

export const VIEW_STRINGS_4: Record<string, Entry> = {
  // ═══ Save that cannot be parsed ═══
  "err.saveUnreadable": { en: "This save could not be read", fr: "Impossible de lire cette sauvegarde", es: "No se pudo leer esta partida", pt: "Não foi possível ler este save", de: "Dieser Spielstand konnte nicht gelesen werden", ru: "Не удалось прочитать это сохранение", pl: "Nie udało się odczytać tego zapisu", zh: "无法读取此存档", ja: "このセーブを読み込めませんでした", hi: "यह सेव पढ़ा नहीं जा सका", ar: "تعذّرت قراءة ملف الحفظ هذا", bn: "এই সেভটি পড়া যায়নি", ur: "یہ سیو پڑھا نہیں جا سکا" },
  "err.saveFormat": { en: "The format does not match what was expected. Pick another slot, or locate the right save folder.", fr: "Le format ne correspond pas à ce qui était attendu. Choisis un autre slot, ou localise le bon dossier de sauvegarde.", es: "El formato no coincide con lo esperado. Elige otra ranura o localiza la carpeta de partidas correcta.", pt: "O formato não corresponde ao esperado. Escolha outro slot ou localize a pasta de saves correta.", de: "Das Format entspricht nicht dem Erwarteten. Wähle einen anderen Slot oder finde den richtigen Spielstand-Ordner.", ru: "Формат не соответствует ожидаемому. Выберите другой слот или укажите правильную папку сохранений.", pl: "Format nie odpowiada oczekiwanemu. Wybierz inny slot lub wskaż właściwy folder zapisów.", zh: "格式与预期不符。请选择其他存档位，或定位正确的存档文件夹。", ja: "形式が想定と異なります。別のスロットを選ぶか、正しいセーブフォルダーを指定してください。", hi: "प्रारूप अपेक्षित से मेल नहीं खाता। दूसरा स्लॉट चुनें, या सही सेव फ़ोल्डर खोजें।", ar: "التنسيق لا يطابق المتوقَّع. اختر خانة أخرى أو حدِّد مجلد الحفظ الصحيح.", bn: "ফরম্যাট প্রত্যাশিতের সাথে মেলে না। অন্য স্লট বেছে নিন, বা সঠিক সেভ ফোল্ডার খুঁজুন।", ur: "فارمیٹ متوقع سے میل نہیں کھاتا۔ دوسرا سلاٹ منتخب کریں، یا درست سیو فولڈر تلاش کریں۔" },
  "err.chooseAnother": { en: "Choose another save", fr: "Choisir une autre sauvegarde", es: "Elegir otra partida", pt: "Escolher outro save", de: "Anderen Spielstand wählen", ru: "Выбрать другое сохранение", pl: "Wybierz inny zapis", zh: "选择其他存档", ja: "別のセーブを選ぶ", hi: "दूसरा सेव चुनें", ar: "اختيار ملف حفظ آخر", bn: "অন্য সেভ বেছে নিন", ur: "دوسرا سیو منتخب کریں" },

  // ═══ Chrome / toasts ═══
  "common.progressUpdated": { en: "Progress updated ✓", fr: "Progression mise à jour ✓", es: "Progreso actualizado ✓", pt: "Progresso atualizado ✓", de: "Fortschritt aktualisiert ✓", ru: "Прогресс обновлён ✓", pl: "Postęp zaktualizowany ✓", zh: "进度已更新 ✓", ja: "進捗を更新しました ✓", hi: "प्रगति अपडेट हुई ✓", ar: "تم تحديث التقدّم ✓", bn: "অগ্রগতি হালনাগাদ হয়েছে ✓", ur: "پیش رفت اپ ڈیٹ ہو گئی ✓" },
  "common.progressUpdatedLive": { en: "Progress updated ✓ (live)", fr: "Progression mise à jour ✓ (live)", es: "Progreso actualizado ✓ (en vivo)", pt: "Progresso atualizado ✓ (ao vivo)", de: "Fortschritt aktualisiert ✓ (live)", ru: "Прогресс обновлён ✓ (в реальном времени)", pl: "Postęp zaktualizowany ✓ (na żywo)", zh: "进度已更新 ✓（实时）", ja: "進捗を更新しました ✓（ライブ）", hi: "प्रगति अपडेट हुई ✓ (लाइव)", ar: "تم تحديث التقدّم ✓ (مباشر)", bn: "অগ্রগতি হালনাগাদ হয়েছে ✓ (লাইভ)", ur: "پیش رفت اپ ڈیٹ ہو گئی ✓ (لائیو)" },
  "theme.label": { en: "Theme", fr: "Thème", es: "Tema", pt: "Tema", de: "Design", ru: "Тема", pl: "Motyw", zh: "主题", ja: "テーマ", hi: "थीम", ar: "السمة", bn: "থিম", ur: "تھیم" },

  // ═══ Stats mod onboarding ═══
  "mod.installedToast": { en: "Mod installed ✓ — relaunch Isaac to enable it", fr: "Mod installé ✓ — relance Isaac pour l'activer", es: "Mod instalado ✓ — reinicia Isaac para activarlo", pt: "Mod instalado ✓ — reinicie o Isaac para ativá-lo", de: "Mod installiert ✓ — starte Isaac neu, um sie zu aktivieren", ru: "Мод установлен ✓ — перезапустите Isaac, чтобы включить его", pl: "Mod zainstalowany ✓ — uruchom ponownie Isaaca, aby go włączyć", zh: "模组已安装 ✓ —— 重启 Isaac 以启用", ja: "Mod をインストールしました ✓ — Isaac を再起動して有効化してください", hi: "मॉड इंस्टॉल हुआ ✓ — सक्षम करने के लिए Isaac फिर से चालू करें", ar: "تم تثبيت المود ✓ — أعد تشغيل Isaac لتفعيله", bn: "মড ইনস্টল হয়েছে ✓ — চালু করতে Isaac আবার চালু করুন", ur: "ماڈ انسٹال ہو گیا ✓ — فعال کرنے کے لیے Isaac دوبارہ چلائیں" },
  "mod.stepNotFound": { en: "Game not found yet — see the Diagnostic tab to locate Isaac.", fr: "Jeu introuvable pour l'instant — vois l'onglet Diagnostic pour localiser Isaac.", es: "Juego no encontrado todavía — usa la pestaña Diagnóstico para localizar Isaac.", pt: "Jogo ainda não encontrado — use a aba Diagnóstico para localizar o Isaac.", de: "Spiel noch nicht gefunden — nutze den Tab Diagnose, um Isaac zu finden.", ru: "Игра пока не найдена — откройте вкладку «Диагностика», чтобы указать Isaac.", pl: "Nie znaleziono jeszcze gry — otwórz kartę Diagnostyka, aby wskazać Isaaca.", zh: "尚未找到游戏 —— 请在「诊断」标签页中定位 Isaac。", ja: "ゲームがまだ見つかりません — 「診断」タブで Isaac の場所を指定してください。", hi: "गेम अभी नहीं मिला — Isaac खोजने के लिए डायग्नोस्टिक टैब देखें।", ar: "لم يُعثر على اللعبة بعد — راجع تبويب التشخيص لتحديد موقع Isaac.", bn: "গেম এখনো পাওয়া যায়নি — Isaac খুঁজতে ডায়াগনস্টিক ট্যাব দেখুন।", ur: "گیم ابھی نہیں ملی — Isaac تلاش کرنے کے لیے تشخیص ٹیب دیکھیں۔" },
  "mod.stepInstall": { en: "Install the companion mod (one click), relaunch Isaac, and it will count your hits and stats on every run — cross-referenced with your completion.", fr: "Installe le mod compagnon (1 clic), relance Isaac, et il comptera tes hits + stats à chaque run — croisés avec ta complétion.", es: "Instala el mod complementario (un clic), reinicia Isaac y contará tus golpes y estadísticas en cada partida — cruzados con tu progreso.", pt: "Instale o mod complementar (um clique), reinicie o Isaac e ele contará seus hits e estatísticas em cada run — cruzados com sua conclusão.", de: "Installiere die Begleit-Mod (ein Klick), starte Isaac neu, und sie zählt deine Treffer und Statistiken in jedem Run — abgeglichen mit deinem Fortschritt.", ru: "Установите мод-компаньон (в один клик) и перезапустите Isaac — он будет считать удары и статистику в каждом забеге, сопоставляя их с прогрессом.", pl: "Zainstaluj mod towarzyszący (jedno kliknięcie), uruchom ponownie Isaaca, a policzy on twoje trafienia i statystyki w każdym runie — zestawione z twoim postępem.", zh: "一键安装配套模组，重启 Isaac，它就会统计你每局的受击与数据 —— 并与完成度交叉对照。", ja: "コンパニオン Mod をワンクリックでインストールし、Isaac を再起動すれば、毎回のランの被弾と統計を記録します — 達成度と突き合わせて表示されます。", hi: "साथी मॉड इंस्टॉल करें (एक क्लिक), Isaac फिर से चालू करें, और यह हर रन में आपके हिट्स और आँकड़े गिनेगा — आपकी पूर्णता से मिलाकर।", ar: "ثبِّت المود المرافق (بنقرة واحدة)، وأعد تشغيل Isaac، وسيحصي إصاباتك وإحصاءاتك في كل جولة — مقارَنةً بنسبة إكمالك.", bn: "সহযোগী মডটি ইনস্টল করুন (এক ক্লিক), Isaac আবার চালু করুন, আর এটি প্রতি রানে আপনার হিট ও পরিসংখ্যান গুনবে — আপনার সম্পূর্ণতার সাথে মিলিয়ে।", ur: "ساتھی ماڈ انسٹال کریں (ایک کلک)، Isaac دوبارہ چلائیں، اور یہ ہر رن میں آپ کے ہٹس اور اعداد و شمار گنے گا — آپ کی تکمیل کے ساتھ ملا کر۔" },
  "mod.stepPlay": { en: "Mod installed ✓. Relaunch Isaac and play a run: the first stats will show up here automatically.", fr: "Mod installé ✓. Relance Isaac et joue un run : les premières stats apparaîtront ici automatiquement.", es: "Mod instalado ✓. Reinicia Isaac y juega una partida: las primeras estadísticas aparecerán aquí automáticamente.", pt: "Mod instalado ✓. Reinicie o Isaac e jogue uma run: as primeiras estatísticas aparecerão aqui automaticamente.", de: "Mod installiert ✓. Starte Isaac neu und spiele einen Run: Die ersten Statistiken erscheinen hier automatisch.", ru: "Мод установлен ✓. Перезапустите Isaac и сыграйте забег: первая статистика появится здесь автоматически.", pl: "Mod zainstalowany ✓. Uruchom ponownie Isaaca i zagraj run: pierwsze statystyki pojawią się tu automatycznie.", zh: "模组已安装 ✓。重启 Isaac 并玩一局：首批数据会自动显示在这里。", ja: "Mod をインストールしました ✓。Isaac を再起動してランをプレイすると、最初の統計がここに自動で表示されます。", hi: "मॉड इंस्टॉल हुआ ✓। Isaac फिर से चालू करें और एक रन खेलें: पहले आँकड़े यहाँ अपने-आप दिखेंगे।", ar: "تم تثبيت المود ✓. أعد تشغيل Isaac والعب جولة: ستظهر أول الإحصاءات هنا تلقائيًا.", bn: "মড ইনস্টল হয়েছে ✓। Isaac আবার চালু করে একটি রান খেলুন: প্রথম পরিসংখ্যান এখানে স্বয়ংক্রিয়ভাবে দেখা যাবে।", ur: "ماڈ انسٹال ہو گیا ✓۔ Isaac دوبارہ چلائیں اور ایک رن کھیلیں: پہلے اعداد و شمار یہاں خودکار طور پر ظاہر ہوں گے۔" },
  "mod.installBtn": { en: "Install the mod", fr: "Installer le mod", es: "Instalar el mod", pt: "Instalar o mod", de: "Mod installieren", ru: "Установить мод", pl: "Zainstaluj mod", zh: "安装模组", ja: "Mod をインストール", hi: "मॉड इंस्टॉल करें", ar: "تثبيت المود", bn: "মড ইনস্টল করুন", ur: "ماڈ انسٹال کریں" },
  "mod.launchFail": { en: "Could not launch Isaac:", fr: "Impossible de lancer Isaac :", es: "No se pudo iniciar Isaac:", pt: "Não foi possível iniciar o Isaac:", de: "Isaac konnte nicht gestartet werden:", ru: "Не удалось запустить Isaac:", pl: "Nie udało się uruchomić Isaaca:", zh: "无法启动 Isaac：", ja: "Isaac を起動できませんでした:", hi: "Isaac चालू नहीं हो सका:", ar: "تعذّر تشغيل Isaac:", bn: "Isaac চালু করা যায়নি:", ur: "Isaac چلایا نہیں جا سکا:" },
  "mod.launchBtn": { en: "Launch Isaac", fr: "Lancer Isaac", es: "Iniciar Isaac", pt: "Iniciar o Isaac", de: "Isaac starten", ru: "Запустить Isaac", pl: "Uruchom Isaaca", zh: "启动 Isaac", ja: "Isaac を起動", hi: "Isaac चालू करें", ar: "تشغيل Isaac", bn: "Isaac চালু করুন", ur: "Isaac چلائیں" },

  // ═══ Achievements browser ═══
  "ach.spoilerTitle": { en: "Show the conditions of locked achievements (spoilers)", fr: "Afficher les conditions des succès verrouillés (spoilers)", es: "Mostrar las condiciones de los logros bloqueados (spoilers)", pt: "Mostrar as condições das conquistas bloqueadas (spoilers)", de: "Bedingungen gesperrter Erfolge anzeigen (Spoiler)", ru: "Показать условия закрытых достижений (спойлеры)", pl: "Pokaż warunki zablokowanych osiągnięć (spoilery)", zh: "显示未解锁成就的条件（剧透）", ja: "未解除の実績の条件を表示（ネタバレ）", hi: "बंद उपलब्धियों की शर्तें दिखाएँ (स्पॉइलर)", ar: "إظهار شروط الإنجازات المقفلة (حرق للأحداث)", bn: "লক করা অর্জনের শর্ত দেখান (স্পয়লার)", ur: "مقفل کامیابیوں کی شرائط دکھائیں (سپائلر)" },
  "ach.spoilersShown": { en: "Spoilers shown", fr: "Spoilers affichés", es: "Spoilers mostrados", pt: "Spoilers exibidos", de: "Spoiler sichtbar", ru: "Спойлеры показаны", pl: "Spoilery widoczne", zh: "已显示剧透", ja: "ネタバレ表示中", hi: "स्पॉइलर दिख रहे हैं", ar: "الحرق ظاهر", bn: "স্পয়লার দেখানো হচ্ছে", ur: "سپائلر دکھائے جا رہے ہیں" },
  "ach.revealConds": { en: "Reveal conditions", fr: "Révéler conditions", es: "Revelar condiciones", pt: "Revelar condições", de: "Bedingungen zeigen", ru: "Показать условия", pl: "Pokaż warunki", zh: "显示条件", ja: "条件を表示", hi: "शर्तें दिखाएँ", ar: "كشف الشروط", bn: "শর্ত প্রকাশ করুন", ur: "شرائط ظاہر کریں" },
  "ach.countSuffix": { en: "achievements", fr: "succès", es: "logros", pt: "conquistas", de: "Erfolge", ru: "достижений", pl: "osiągnięć", zh: "个成就", ja: "件の実績", hi: "उपलब्धियाँ", ar: "إنجازًا", bn: "অর্জন", ur: "کامیابیاں" },
  "ach.unlockedSuffix": { en: "unlocked", fr: "débloqués", es: "desbloqueados", pt: "desbloqueadas", de: "freigeschaltet", ru: "открыто", pl: "odblokowanych", zh: "已解锁", ja: "解除済み", hi: "अनलॉक", ar: "مفتوح", bn: "আনলক", ur: "انلاک" },

  // ═══ Build assistant ═══
  "bld.tearReplacement": { en: "tear replacement", fr: "remplacement de larmes", es: "reemplazo de lágrimas", pt: "substituição de lágrimas", de: "Tränen-Ersatz", ru: "замена слёз", pl: "zamiana łez", zh: "眼泪替换", ja: "ティア置換", hi: "टियर रिप्लेसमेंट", ar: "استبدال الدموع", bn: "টিয়ার প্রতিস্থাপন", ur: "ٹیئر تبدیلی" },

  // ═══ Diagnostic ═══
  "diag.willBeCreated": { en: "will be created when the mod is installed", fr: "sera créé à l'installation du mod", es: "se creará al instalar el mod", pt: "será criado na instalação do mod", de: "wird bei der Mod-Installation erstellt", ru: "будет создана при установке мода", pl: "zostanie utworzony przy instalacji moda", zh: "将在安装模组时创建", ja: "Mod のインストール時に作成されます", hi: "मॉड इंस्टॉल होने पर बनेगा", ar: "سيُنشأ عند تثبيت المود", bn: "মড ইনস্টল করলে তৈরি হবে", ur: "ماڈ انسٹال ہونے پر بنے گا" },
  "diag.createdFirstRun": { en: "created on the first run with the mod", fr: "créé au premier run avec le mod", es: "se crea en la primera partida con el mod", pt: "criado na primeira run com o mod", de: "wird beim ersten Run mit der Mod erstellt", ru: "создаётся при первом забеге с модом", pl: "tworzony przy pierwszym runie z modem", zh: "将在装有模组的首局游戏时创建", ja: "Mod を入れた最初のランで作成されます", hi: "मॉड के साथ पहले रन पर बनेगा", ar: "يُنشأ في أول جولة مع المود", bn: "মড নিয়ে প্রথম রানে তৈরি হয়", ur: "ماڈ کے ساتھ پہلے رن پر بنے گا" },
  "diag.saveLoaded": { en: "Save loaded:", fr: "Save chargée :", es: "Partida cargada:", pt: "Save carregado:", de: "Spielstand geladen:", ru: "Сохранение загружено:", pl: "Zapis wczytany:", zh: "已加载存档：", ja: "セーブ読み込み済み:", hi: "सेव लोड हुआ:", ar: "تم تحميل ملف الحفظ:", bn: "সেভ লোড হয়েছে:", ur: "سیو لوڈ ہو گیا:" },
  "diag.noSaveLoaded": { en: "No save loaded", fr: "Aucune save chargée", es: "Ninguna partida cargada", pt: "Nenhum save carregado", de: "Kein Spielstand geladen", ru: "Сохранение не загружено", pl: "Nie wczytano zapisu", zh: "未加载存档", ja: "セーブ未読み込み", hi: "कोई सेव लोड नहीं", ar: "لم يُحمَّل أي ملف حفظ", bn: "কোনো সেভ লোড হয়নি", ur: "کوئی سیو لوڈ نہیں" },
  "diag.checksum": { en: "Checksum", fr: "Checksum", es: "Suma de verificación", pt: "Checksum", de: "Prüfsumme", ru: "Контрольная сумма", pl: "Suma kontrolna", zh: "校验和", ja: "チェックサム", hi: "चेकसम", ar: "المجموع الاختباري", bn: "চেকসাম", ur: "چیک سم" },
  "diag.invalid": { en: "invalid", fr: "invalide", es: "no válida", pt: "inválido", de: "ungültig", ru: "неверна", pl: "nieprawidłowa", zh: "无效", ja: "無効", hi: "अमान्य", ar: "غير صالح", bn: "অবৈধ", ur: "غلط" },
  "diag.marksWord": { en: "marks", fr: "marques", es: "marcas", pt: "marcas", de: "Marken", ru: "метки", pl: "znaczniki", zh: "标记", ja: "マーク", hi: "मार्क", ar: "العلامات", bn: "মার্ক", ur: "مارکس" },
  "diag.reliable": { en: "reliable", fr: "fiables", es: "fiables", pt: "confiáveis", de: "zuverlässig", ru: "надёжны", pl: "wiarygodne", zh: "可靠", ja: "信頼できる", hi: "विश्वसनीय", ar: "موثوقة", bn: "নির্ভরযোগ্য", ur: "قابلِ اعتماد" },
  "diag.notReliable": { en: "NOT reliable (override recommended)", fr: "NON fiables (override recommandé)", es: "NO fiables (se recomienda una corrección)", pt: "NÃO confiáveis (correção recomendada)", de: "NICHT zuverlässig (Korrektur empfohlen)", ru: "НЕ надёжны (рекомендуется правка)", pl: "NIE wiarygodne (zalecana korekta)", zh: "不可靠（建议手动修正）", ja: "信頼できません（手動修正を推奨）", hi: "विश्वसनीय नहीं (सुधार अनुशंसित)", ar: "غير موثوقة (يُنصح بالتصحيح اليدوي)", bn: "নির্ভরযোগ্য নয় (সংশোধন সুপারিশকৃত)", ur: "قابلِ اعتماد نہیں (تصحیح تجویز کردہ)" },
  "diag.momBeaten": { en: "Mom beaten on this slot", fr: "Mom battue sur ce slot", es: "Mom derrotada en esta ranura", pt: "Mom derrotada neste slot", de: "Mom in diesem Slot besiegt", ru: "Mom побеждена в этом слоте", pl: "Mom pokonana w tym slocie", zh: "该存档位已击败 Mom", ja: "このスロットで Mom 撃破済み", hi: "इस स्लॉट में Mom हराई गई", ar: "تمت هزيمة Mom في هذه الخانة", bn: "এই স্লটে Mom পরাজিত", ur: "اس سلاٹ میں Mom کو شکست دی گئی" },
  "diag.momWarn": { en: "⚠ On a fresh save, mods block unlocks until Mom has been beaten once (a rule of the game).", fr: "⚠ Sur une nouvelle save, les mods bloquent les déblocages tant que Mom n'a pas été battue une fois (règle du jeu).", es: "⚠ En una partida nueva, los mods bloquean los desbloqueos hasta haber derrotado a Mom una vez (regla del juego).", pt: "⚠ Em um save novo, os mods bloqueiam os desbloqueios até Mom ser derrotada uma vez (regra do jogo).", de: "⚠ Auf einem neuen Spielstand blockieren Mods die Freischaltungen, bis Mom einmal besiegt wurde (Spielregel).", ru: "⚠ На новом сохранении моды блокируют открытия, пока Mom не побеждена хотя бы раз (правило игры).", pl: "⚠ Na nowym zapisie mody blokują odblokowania, dopóki Mom nie zostanie raz pokonana (zasada gry).", zh: "⚠ 在全新存档上，未击败过 Mom 之前模组会禁用解锁（游戏机制）。", ja: "⚠ 新規セーブでは、Mom を一度倒すまで Mod がアンロックを無効化します（ゲームの仕様）。", hi: "⚠ नए सेव पर, जब तक Mom को एक बार हराया न जाए, मॉड अनलॉक रोक देते हैं (गेम का नियम)।", ar: "⚠ في ملف حفظ جديد، تمنع المودات فتح الإنجازات حتى تُهزم Mom مرة واحدة (قاعدة في اللعبة).", bn: "⚠ নতুন সেভে, Mom একবার পরাজিত না হওয়া পর্যন্ত মড আনলক আটকে রাখে (গেমের নিয়ম)।", ur: "⚠ نئے سیو پر، جب تک Mom کو ایک بار شکست نہ دی جائے، ماڈز انلاک روک دیتے ہیں (گیم کا اصول)۔" },
  "diag.momOk": { en: "Mods block no unlock on this slot.", fr: "Les mods ne bloquent aucun déblocage sur ce slot.", es: "Los mods no bloquean ningún desbloqueo en esta ranura.", pt: "Os mods não bloqueiam nenhum desbloqueio neste slot.", de: "Mods blockieren in diesem Slot keine Freischaltungen.", ru: "Моды не блокируют открытия в этом слоте.", pl: "Mody nie blokują żadnych odblokowań w tym slocie.", zh: "该存档位上模组不会阻止任何解锁。", ja: "このスロットでは Mod がアンロックを妨げません。", hi: "इस स्लॉट पर मॉड किसी अनलॉक को नहीं रोकते।", ar: "لا تمنع المودات أي فتح في هذه الخانة.", bn: "এই স্লটে মড কোনো আনলক আটকায় না।", ur: "اس سلاٹ پر ماڈز کوئی انلاک نہیں روکتے۔" },
  "diag.modDataPresent": { en: "Mod data present", fr: "Données du mod présentes", es: "Datos del mod presentes", pt: "Dados do mod presentes", de: "Mod-Daten vorhanden", ru: "Данные мода найдены", pl: "Dane moda obecne", zh: "已有模组数据", ja: "Mod データあり", hi: "मॉड डेटा मौजूद", ar: "بيانات المود موجودة", bn: "মড ডেটা রয়েছে", ur: "ماڈ ڈیٹا موجود" },
  "diag.modDataNone": { en: "none (play a run with the mod enabled)", fr: "aucune (fais un run avec le mod activé)", es: "ninguno (juega una partida con el mod activado)", pt: "nenhum (jogue uma run com o mod ativado)", de: "keine (spiele einen Run mit aktivierter Mod)", ru: "нет (сыграйте забег с включённым модом)", pl: "brak (zagraj run z włączonym modem)", zh: "无（启用模组后玩一局）", ja: "なし（Mod を有効にしてランをプレイ）", hi: "कोई नहीं (मॉड चालू करके एक रन खेलें)", ar: "لا شيء (العب جولة مع تفعيل المود)", bn: "নেই (মড চালু করে একটি রান খেলুন)", ur: "کوئی نہیں (ماڈ فعال کر کے ایک رن کھیلیں)" },
  "diag.reinstallMod": { en: "Reinstall the stats mod", fr: "Réinstaller le mod de stats", es: "Reinstalar el mod de estadísticas", pt: "Reinstalar o mod de estatísticas", de: "Statistik-Mod neu installieren", ru: "Переустановить мод статистики", pl: "Zainstaluj ponownie mod statystyk", zh: "重新安装统计模组", ja: "統計 Mod を再インストール", hi: "स्टैट्स मॉड फिर से इंस्टॉल करें", ar: "إعادة تثبيت مود الإحصاءات", bn: "স্ট্যাটস মড পুনরায় ইনস্টল করুন", ur: "اعداد و شمار ماڈ دوبارہ انسٹال کریں" },
  "diag.installMod": { en: "Install the stats mod", fr: "Installer le mod de stats", es: "Instalar el mod de estadísticas", pt: "Instalar o mod de estatísticas", de: "Statistik-Mod installieren", ru: "Установить мод статистики", pl: "Zainstaluj mod statystyk", zh: "安装统计模组", ja: "統計 Mod をインストール", hi: "स्टैट्स मॉड इंस्टॉल करें", ar: "تثبيت مود الإحصاءات", bn: "স্ট্যাটস মড ইনস্টল করুন", ur: "اعداد و شمار ماڈ انسٹال کریں" },

  // ═══ Stat card ═══
  "card.renderFail": { en: "Canvas rendering failed.", fr: "Rendu du canvas impossible.", es: "No se pudo renderizar el lienzo.", pt: "Falha ao renderizar o canvas.", de: "Canvas-Rendering fehlgeschlagen.", ru: "Не удалось отрисовать холст.", pl: "Renderowanie płótna nie powiodło się.", zh: "画布渲染失败。", ja: "キャンバスの描画に失敗しました。", hi: "कैनवास रेंडर नहीं हो सका।", ar: "فشل رسم اللوحة.", bn: "ক্যানভাস রেন্ডার করা যায়নি।", ur: "کینوس رینڈر نہیں ہو سکا۔" },

  // ═══ Achievement categories (lib/format.ts) ═══
  "cat.character": { en: "Characters", fr: "Personnages", es: "Personajes", pt: "Personagens", de: "Charaktere", ru: "Персонажи", pl: "Postacie", zh: "角色", ja: "キャラクター", hi: "किरदार", ar: "الشخصيات", bn: "চরিত্র", ur: "کردار" },
  "cat.item": { en: "Items", fr: "Objets", es: "Objetos", pt: "Itens", de: "Items", ru: "Предметы", pl: "Przedmioty", zh: "道具", ja: "アイテム", hi: "आइटम", ar: "العناصر", bn: "আইটেম", ur: "آئٹمز" },
  "cat.trinket": { en: "Trinkets", fr: "Breloques", es: "Baratijas", pt: "Bugigangas", de: "Schmuckstücke", ru: "Безделушки", pl: "Bibeloty", zh: "饰品", ja: "トリンケット", hi: "ट्रिंकेट", ar: "التمائم", bn: "ট্রিংকেট", ur: "ٹرنکٹس" },
  "cat.pill": { en: "Pills", fr: "Pilules", es: "Píldoras", pt: "Pílulas", de: "Pillen", ru: "Таблетки", pl: "Pigułki", zh: "药丸", ja: "ピル", hi: "गोलियाँ", ar: "الحبوب", bn: "পিল", ur: "گولیاں" },
  "cat.card": { en: "Cards / Runes", fr: "Cartes / Runes", es: "Cartas / Runas", pt: "Cartas / Runas", de: "Karten / Runen", ru: "Карты / Руны", pl: "Karty / Runy", zh: "卡牌 / 符文", ja: "カード / ルーン", hi: "कार्ड / रून", ar: "البطاقات / الرونات", bn: "কার্ড / রুন", ur: "کارڈز / رونز" },
  "cat.coop_baby": { en: "Co-op babies", fr: "Bébés co-op", es: "Bebés cooperativos", pt: "Bebês co-op", de: "Koop-Babys", ru: "Ко-оп малыши", pl: "Bobasy co-op", zh: "合作宝宝", ja: "co-op ベビー", hi: "को-ऑप बेबी", ar: "أطفال التعاون", bn: "কো-অপ বেবি", ur: "کو-آپ بیبیز" },
  "cat.challenge": { en: "Challenges", fr: "Challenges", es: "Desafíos", pt: "Desafios", de: "Herausforderungen", ru: "Испытания", pl: "Wyzwania", zh: "挑战", ja: "チャレンジ", hi: "चैलेंज", ar: "التحديات", bn: "চ্যালেঞ্জ", ur: "چیلنجز" },
  "cat.completion_mark": { en: "Completion marks", fr: "Completion marks", es: "Marcas de completado", pt: "Marcas de conclusão", de: "Abschluss-Marken", ru: "Метки завершения", pl: "Znaczniki ukończenia", zh: "完成标记", ja: "コンプリートマーク", hi: "कम्प्लीशन मार्क", ar: "علامات الإكمال", bn: "কমপ্লিশন মার্ক", ur: "کمپلیشن مارکس" },
  "cat.boss": { en: "Boss", fr: "Boss", es: "Jefes", pt: "Chefes", de: "Bosse", ru: "Боссы", pl: "Bossowie", zh: "Boss", ja: "ボス", hi: "बॉस", ar: "الزعماء", bn: "বস", ur: "باس" },
  "cat.misc": { en: "Misc", fr: "Divers", es: "Varios", pt: "Diversos", de: "Sonstiges", ru: "Разное", pl: "Różne", zh: "其他", ja: "その他", hi: "विविध", ar: "متنوّع", bn: "বিবিধ", ur: "متفرق" },

  // ═══ Item roles (lib/format.ts) ═══
  "role.offensive": { en: "Offensive", fr: "Offensif", es: "Ofensivo", pt: "Ofensivo", de: "Offensiv", ru: "Атака", pl: "Ofensywny", zh: "输出", ja: "攻撃", hi: "आक्रामक", ar: "هجومي", bn: "আক্রমণাত্মক", ur: "جارحانہ" },
  "role.defensive": { en: "Defensive", fr: "Défensif", es: "Defensivo", pt: "Defensivo", de: "Defensiv", ru: "Защита", pl: "Defensywny", zh: "防御", ja: "防御", hi: "रक्षात्मक", ar: "دفاعي", bn: "রক্ষণাত্মক", ur: "دفاعی" },
  "role.mobility": { en: "Mobility", fr: "Mobilité", es: "Movilidad", pt: "Mobilidade", de: "Mobilität", ru: "Мобильность", pl: "Mobilność", zh: "机动", ja: "機動力", hi: "गतिशीलता", ar: "الحركة", bn: "গতিশীলতা", ur: "نقل و حرکت" },
  "role.tear_mod": { en: "Tear modifier", fr: "Modif. de tirs", es: "Modificador de lágrimas", pt: "Modificador de lágrimas", de: "Tränen-Modifikator", ru: "Модификатор слёз", pl: "Modyfikator łez", zh: "眼泪改造", ja: "ティア変化", hi: "टियर मॉडिफायर", ar: "معدِّل الدموع", bn: "টিয়ার মডিফায়ার", ur: "ٹیئر موڈیفائر" },
  "role.utility": { en: "Utility", fr: "Utilitaire", es: "Utilidad", pt: "Utilidade", de: "Utility", ru: "Утилита", pl: "Użytkowy", zh: "功能", ja: "ユーティリティ", hi: "यूटिलिटी", ar: "مساعد", bn: "ইউটিলিটি", ur: "افادیت" },
  "role.familiar": { en: "Familiar", fr: "Familier", es: "Familiar", pt: "Familiar", de: "Begleiter", ru: "Фамильяр", pl: "Chowaniec", zh: "跟班", ja: "ファミリア", hi: "फैमिलियर", ar: "التابع", bn: "ফ্যামিলিয়ার", ur: "فیملیئر" },

  // ═══ Tear flags (lib/format.ts) ═══
  "tflag.homing": { en: "homing", fr: "auto-visée", es: "teledirigido", pt: "teleguiado", de: "zielsuchend", ru: "самонаводящиеся", pl: "samonaprowadzające", zh: "追踪", ja: "ホーミング", hi: "होमिंग", ar: "متعقِّب", bn: "হোমিং", ur: "ہومنگ" },
  "tflag.piercing": { en: "piercing", fr: "perçant", es: "perforante", pt: "perfurante", de: "durchdringend", ru: "пробивающие", pl: "przebijające", zh: "穿透", ja: "貫通", hi: "भेदक", ar: "خارق", bn: "ভেদক", ur: "چھیدنے والا" },
  "tflag.spectral": { en: "spectral", fr: "spectral", es: "espectral", pt: "espectral", de: "spektral", ru: "призрачные", pl: "widmowe", zh: "穿墙", ja: "スペクトル", hi: "स्पेक्ट्रल", ar: "شبحي", bn: "স্পেকট্রাল", ur: "سپیکٹرل" },
  "tflag.explosive": { en: "explosive", fr: "explosif", es: "explosivo", pt: "explosivo", de: "explosiv", ru: "взрывные", pl: "wybuchowe", zh: "爆炸", ja: "爆発", hi: "विस्फोटक", ar: "متفجّر", bn: "বিস্ফোরক", ur: "دھماکہ خیز" },

  // ═══ Stat dimensions (lib/format.ts) ═══
  "stat.damage": { en: "Damage", fr: "Dégâts", es: "Daño", pt: "Dano", de: "Schaden", ru: "Урон", pl: "Obrażenia", zh: "伤害", ja: "ダメージ", hi: "डैमेज", ar: "الضرر", bn: "ড্যামেজ", ur: "نقصان" },
  "stat.fire_rate": { en: "Fire rate", fr: "Cadence", es: "Cadencia", pt: "Cadência", de: "Feuerrate", ru: "Скорострельность", pl: "Szybkostrzelność", zh: "射速", ja: "連射速度", hi: "फायर रेट", ar: "معدّل الإطلاق", bn: "ফায়ার রেট", ur: "فائر ریٹ" },
  "stat.range": { en: "Range", fr: "Portée", es: "Alcance", pt: "Alcance", de: "Reichweite", ru: "Дальность", pl: "Zasięg", zh: "射程", ja: "射程", hi: "रेंज", ar: "المدى", bn: "রেঞ্জ", ur: "رینج" },
  "stat.shot_speed": { en: "Shot speed", fr: "Vél. tir", es: "Velocidad de disparo", pt: "Velocidade de tiro", de: "Schussgeschwindigkeit", ru: "Скорость выстрела", pl: "Prędkość pocisku", zh: "弹速", ja: "弾速", hi: "शॉट स्पीड", ar: "سرعة الطلقة", bn: "শট স্পিড", ur: "شاٹ اسپیڈ" },
  "stat.speed": { en: "Speed", fr: "Vitesse", es: "Velocidad", pt: "Velocidade", de: "Tempo", ru: "Скорость", pl: "Szybkość", zh: "移速", ja: "移動速度", hi: "स्पीड", ar: "السرعة", bn: "স্পিড", ur: "رفتار" },
  "stat.luck": { en: "Luck", fr: "Chance", es: "Suerte", pt: "Sorte", de: "Glück", ru: "Удача", pl: "Szczęście", zh: "幸运", ja: "運", hi: "लक", ar: "الحظ", bn: "লাক", ur: "قسمت" },

  // ═══ Synergy verdicts (lib/format.ts) ═══
  "verdict.strong_pickup": { en: "Strong pick", fr: "Bon pick", es: "Buena elección", pt: "Boa escolha", de: "Starker Pick", ru: "Отличный выбор", pl: "Mocny wybór", zh: "值得拿", ja: "強い選択", hi: "बढ़िया पिक", ar: "اختيار قوي", bn: "ভালো পিক", ur: "بہترین انتخاب" },
  "verdict.fills_gap": { en: "Fills a gap", fr: "Comble un trou", es: "Cubre un hueco", pt: "Preenche uma lacuna", de: "Schließt eine Lücke", ru: "Закрывает пробел", pl: "Zapełnia lukę", zh: "补足短板", ja: "弱点を補う", hi: "कमी पूरी करता है", ar: "يسدّ ثغرة", bn: "ঘাটতি পূরণ করে", ur: "کمی پوری کرتا ہے" },
  "verdict.situational": { en: "Situational", fr: "Situationnel", es: "Situacional", pt: "Situacional", de: "Situationsabhängig", ru: "Ситуативно", pl: "Sytuacyjny", zh: "看情况", ja: "状況次第", hi: "परिस्थितिजन्य", ar: "حسب الموقف", bn: "পরিস্থিতিনির্ভর", ur: "حالات پر منحصر" },
  "verdict.redundant_or_conflict": { en: "Conflict / redundant", fr: "Conflit / redondant", es: "Conflicto / redundante", pt: "Conflito / redundante", de: "Konflikt / redundant", ru: "Конфликт / избыточно", pl: "Konflikt / zbędny", zh: "冲突 / 冗余", ja: "競合 / 冗長", hi: "टकराव / अनावश्यक", ar: "تعارض / زائد", bn: "সংঘাত / অপ্রয়োজনীয়", ur: "تصادم / غیر ضروری" },

  // ═══ Floors (fallback for an unknown stage number) ═══
  "stage.floor": { en: "Floor", fr: "Étage", es: "Piso", pt: "Andar", de: "Etage", ru: "Этаж", pl: "Piętro", zh: "楼层", ja: "フロア", hi: "फ़्लोर", ar: "الطابق", bn: "ফ্লোর", ur: "منزل" },
};
